import { Area } from "./types";

export const areas: Area[] = [
  { name: "Aegean Archipelago", adjacentSeas: ['Aegean Sea', 'Eastern Mediterranean'], adjacentAreas: ['Greece', "Cyprus", 'Aydin','Macedonia Thrace', 'Cyrenaica', 'Egypt'], hreMember: false, religion: "Orthodox", distant: false },
  { name: "Africa", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: true },
  { name: "Algiers", adjacentSeas: ['Western Mediterranean'], adjacentAreas: ['Northern Morocco', 'Tunisia', 'Suthern Morocco', 'North Sahara'], hreMember: false, religion: "Muslim", distant: false },
  { name: "America", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: true },
  { name: "Andalucia", adjacentSeas: ['Central Atlantic', 'Western Mediterranean'], adjacentAreas: ['Portugal', 'Leon', 'Castile'], hreMember: false, religion: "Diverse Faiths", distant: false },
  { name: "Aquitaine", adjacentSeas: ['Bay of Biscay'], adjacentAreas: ['Aragon', 'Loire', 'Languedoc', 'Brittany Normandy',  ], hreMember: false, religion: "", distant: false },
  { name: "Aragon", adjacentSeas: ['Bay of Biscay', 'Gulf of Lion', 'Western Mediterranean'], adjacentAreas: ['Aquitaine', 'Languedoc', 'Castile'], hreMember: false, religion: "Catholic", distant: false },
  { name: "Armenia", adjacentSeas: [], adjacentAreas: ['Caucasus', 'Iraq', 'Kurdistan', 'Rum', 'Circassia'], hreMember: false, religion: "Diverse Faiths", distant: false },
  { name: "Astrakhan", adjacentSeas: [], adjacentAreas: ['Circassia', 'Caucasus', 'Crimea', 'Saratov'], hreMember: false, religion: "Muslim", distant: false },
  { name: "Austria", adjacentSeas: [], adjacentAreas: [
    'Venetia',
    'Croatia Bosnia',
    'Royal Hungary',
    'Bohemia',
    'Bavaria Swabia',
    'Tirol'
  ], hreMember: false, religion: "Catholic", distant: false },
  { name: "Aydin", adjacentSeas: [
    'Aegean Sea',
    'Eastern Mediterranean',
  ], adjacentAreas: [
    'Northern Anatolia',
    'Karaman'
  ], hreMember: false, religion: "Muslim", distant: false },
  { name: "Bavaria Swabia", adjacentSeas: [], adjacentAreas: [
    'Tirol',
    'Austria',
    'Saxony',
    'Rhineland',
    'Switzerland',
    'Bohemia'
  ], hreMember: false, religion: "Catholic", distant: false },
  { name: "Bohemia", adjacentSeas: [], adjacentAreas: [
    'Saxony',
    'Bavaria Swabia',
    'Wielkopolska',
    'Brandenburg',
    'Austria',
    'Royal Hungary',
  ], hreMember: false, religion: "Catholic", distant: false },
  { name: "Brandenburg", adjacentSeas: [], adjacentAreas: [
    'Bohemia',
    'Saxony',
    'Wielkopolska',
    'Pomerania',
    'Lower Saxony',
    'Prussia',
  ], hreMember: false, religion: "", distant: false },
  { name: "Brittany Normandy", adjacentSeas: [
    'Bay of Biscay',
    'English Channel',
  ], adjacentAreas: [
    'Seine',
    'Loire',
    'Aquitaine'
  ], hreMember: false, religion: "Catholic", distant: false },
  { name: "Burgundy", adjacentSeas: [], adjacentAreas: [
    'Loire',
    'Seine',
    'Languedoc',
    'Rhineland',
    'Switzerland',
    'Lombardy',
  ], hreMember: false, religion: "Catholic", distant: false },
  { name: "Castile", adjacentSeas: [
    'Western Mediterranean',
  ], adjacentAreas: [
    'Aragon',
    'Andalucia',
    'Leon',
  ], hreMember: false, religion: "Catholic", distant: false },
  { name: "Caucasus", adjacentSeas: [], adjacentAreas: [
    'Circassia',
    'Armenia', 
    'Astrakhan',
  ], hreMember: false, religion: "Muslim", distant: false },
  { name: "Central Italy", adjacentSeas: [
    'Adriatic Sea',
    'Gulf of Lion',
    'Central Mediterranean',
  ], adjacentAreas: [
    'Naples',
    'Venetia', 
    'Lombardy'
  ], hreMember: false, religion: "Catholic", distant: false },
  { name: "Central Russia", adjacentSeas: [], adjacentAreas: [
    'Moscow Ryazan',
    'Novgorod',
    'Vologda',
    'Perm', 
    'Kazan',
    'Saratov',
  ], hreMember: false, religion: "Orthodox", distant: false },
  { name: "Circassia", adjacentSeas: ['Black Sea'], adjacentAreas: [
    'Caucassus',
    'Armenia',
    'Astrakhan',
    'Crimea',
    'Rum'
  ], hreMember: false, religion: "Catholic", distant: false },
  { name: "Corsica Sardinia", adjacentSeas: [
    'Mediterranean Sea',
    'Gulf of Lion',
  ], adjacentAreas: [], hreMember: false, religion: "Catholic", distant: false },
  { name: "Crimea", adjacentSeas: ['Black Sea'], adjacentAreas: [
    'Circassia',
    'Western Ukraine',
    'Moldavia',
    'Saratov',
    'Eastern Ukraine',
    'Astrakhan',
  ], hreMember: false, religion: "Muslim", distant: false },
  { name: "Croatia Bosnia", adjacentSeas: [], adjacentAreas: [
    'Dalmatia',
    'Serbia Albania',
    'Hungarian Plain',
    'Royal Hungary',
    'Austria',
    'Venetia'
  ], hreMember: false, religion: "Diverse Faiths", distant: false },
  { name: "Cyprus", adjacentSeas: [
    'Eastern Mediterranean',
  ], adjacentAreas: [], hreMember: false, religion: "Orthodox", distant: false },
  { name: "Cyrenaica", adjacentSeas: [
    'Eastern Mediterranean',
    'Central Mediterranean',
  ], adjacentAreas: [
    'Edypt',
    'Tripolitania',
  ], hreMember: false, religion: "Muslim", distant: false },
  { name: "Dalmatia", adjacentSeas: [
    'Adriatic Sea',
  ], adjacentAreas: [
    'Croatia Bosnia',
    'Venetia', 
    'Serbia Albania',
  ], hreMember: false, religion: "Catholic", distant: false },
  { name: "East Anglia", adjacentSeas: [
    'English Channel',
    'Doggerbank',
  ], adjacentAreas: [
    'Northumbria',
    'Wales Essex'
  ], hreMember: false, religion: "Catholic", distant: false },
  { name: "Eastern Ukraine", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Egypt", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Estonia Livonia", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Far east", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: true },
  { name: "Finland", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Flanders Wallonia", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Gotaland Skane", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Greece", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Hungarian Plain", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "India Arabia", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: true },
  { name: "Iraq", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Ireland", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Jutland", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Karaman", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Karelia", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Kazan", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Kurdistan", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Languedoc", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Leon", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Lithuania", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Loire", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Lombardy", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Lower Saxony", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Macaronesia", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Macedonia Thrace", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Mazovia Malopolska", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Moldavia", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Moscow Ryazan", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Naples", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Netherlands", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Norrland", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "North America", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "North Sahara", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Northen Central Asia", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Northern Anatolia", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Northern Central Asia", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Northern Marroco", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Northumbria", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Novgorod", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Ostlandet", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Ostrobothnia", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Palestine", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Perm", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Pomerania", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Pomorye", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Portugal", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Prussia", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Red Ruthenia", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Rhineland", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Royal Hungary", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Rum", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Saratov", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Saxony", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Scotland", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Seine", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Serbia Albania", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Sicily", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Sjaelland Fyn", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Suthern Marroco", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Svealand", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Switzerland", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Syria", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Tirol", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Transylvania", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Tripolitania", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Trondelag", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Tunisia", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Venetia", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Vestlandet", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Vologda", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Wales Essex", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Wallachia Bulgaria", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Western Ukraine", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Westphalia", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "White Ruthenia", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
  { name: "Wielkopolska", adjacentSeas: [], adjacentAreas: [], hreMember: false, religion: "", distant: false },
];