import { Kingdom } from "./types";

export const kingdoms: Kingdom[] = [
    {
        name: "England",
        capital: "London",
        taxValue: 16,
        vassals: [],
    },
    {
        name: "Aragon",
        capital: "Valencia",
        taxValue: 9,
        vassalsTaxValue: 4,
        vassals: ['Naples'],
    },
    {
        name: "Navarra",
        capital: "Navarra",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Brittany",
        capital: "Nantes",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Castile",
        capital: "Madrid",
        taxValue: 12,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "England",
        capital: "London",
        taxValue: 16,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Desmond",
        capital: "Mhumhain",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Leinster",
        capital: "Leighlin",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Tyrone",
        capital: "Ulaidh",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Provence",
        capital: "Provence",
        taxValue: 3,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Portugal",
        capital: "Lisboa",
        taxValue: 6,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Scotland",
        capital: "Lothian",
        taxValue: 4,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "France",
        capital: "Paris",
        taxValue: 16,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Denmark",
        capital: "Kobenhavn",
        taxValue: 7,
        vassalsTaxValue: 2,
        vassals: ['Holstein'],
    },{
        name: "Sweden",
        capital: "Stockholm",
        taxValue: 7,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Norway",
        capital: "Akershus",
        taxValue: 4,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Tlemcen",
        capital: "Tlemcen",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Morroco",
        capital: "Fez",
        taxValue: 6,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Djerid",
        capital: "Qafsah",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Tunis",
        capital: "Tunis",
        taxValue: 6,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Augsburg",
        capital: "Augsburg",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Bavaria",
        capital: "Munchen",
        taxValue: 3,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Salzburg",
        capital: "Salzburg",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Ulm",
        capital: "Ulm",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Bohemia",
        capital: "Praha",
        taxValue: 5,
        vassalsTaxValue: 1,
        vassals: ['Silesia'],
    },{
        name: "Brandenburg",
        capital: "Berlin",
        taxValue: 3,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Burgundy",
        capital: "Bourgogne",
        taxValue: 7,
        vassalsTaxValue: 6,
        vassals: ['Antwerpen', 'Brugge'],
    },{
        name: "Savoy",
        capital: "Savoie",
        taxValue: 4,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Brabant",
        capital: "Antwerpen",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Flanders",
        capital: "Brugge",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Liege",
        capital: "Liege",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Holstein",
        capital: "Holstein",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Bremen",
        capital: "Bremen",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Brunswick",
        capital: "Braunschweig",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Hamburg",
        capital: "Hamburg",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Magdeburg",
        capital: "Magdeburg",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Friesland",
        capital: "Friesland",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Gelre",
        capital: "Gelre",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Holland",
        capital: "Amsterdam",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Lubeck",
        capital: "Lubeck",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Mecklenburg",
        capital: "Mecklenburg",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Pomerania",
        capital: "Stettin",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Lorraine",
        capital: "Lorraine",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Mainz",
        capital: "Mainz",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "The Palatinate",
        capital: "Pfalz",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Nuremberg",
        capital: "Nurnberg",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Saxony",
        capital: "Dresden",
        taxValue: 3,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Cleves",
        capital: "Kleve",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Cologne",
        capital: "Koln",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Frankfurt",
        capital: "Frankfurt",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Munster",
        capital: "Munster",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Trier",
        capital: "Trier",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Silesia",
        capital: "Silesia",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Austria",
        capital: "Wien",
        taxValue: 9,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Ferrara",
        capital: "Ferrara",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Florence",
        capital: "Firenze",
        taxValue: 3,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Papal States",
        capital: "Roma",
        taxValue: 4,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Siena",
        capital: "Siena",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Genoa",
        capital: "Genova",
        taxValue: 4,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Mantua",
        capital: "Mantova",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Milan",
        capital: "MIlano",
        taxValue: 4,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Naples",
        capital: "Napoli",
        taxValue: 4,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Switzerland",
        capital: "Bern",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Venice",
        capital: "Venezia",
        taxValue: 7,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Knights",
        capital: "Rhodes",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Hungary",
        capital: "Pest",
        taxValue: 8,
        vassalsTaxValue: 2,
        vassals: ['Zagreb'],
    },
    {
        name: "Bosnia",
        capital: "Bosnia",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Croatia",
        capital: "Zagreb",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Ragusa",
        capital: "Ragusa",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Poland",
        capital: "Krakow",
        taxValue: 9,
        vassalsTaxValue: 3,
        vassals: ['Suceava', 'Warszawa'],
    },
    {
        name: "Ottomans",
        capital: "Edirne",
        taxValue: 15,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Teutonic Order",
        capital: "Marienburg",
        taxValue: 4,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Central America",
        capital: "Central America",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Aztec",
        capital: "Mexico",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Inca",
        capital: "Cuzco",
        taxValue: 5,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Adal",
        capital: "Adal",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Ajuuraan",
        capital: "Ajuuraan",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Benin",
        capital: "Benin",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Central Africa",
        capital: "Central Africa",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Ethiopia",
        capital: "Ethiopia",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Katsina",
        capital: "Katsina",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Kilwa",
        capital: "Kilwa",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Kongo",
        capital: "Kongo",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Madagascar",
        capital: "Madagascar",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Mali",
        capital: "Mali",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Mutapa",
        capital: "Mutapa",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Songhai",
        capital: "Songhai",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Timbuktu",
        capital: "Timbuktu",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Mamluks",
        capital: "Qahirah",
        taxValue: 15,
        vassalsTaxValue: 1,
        vassals: ['Hejaz'],
    },{
        name: "Hejaz",
        capital: "Hejaz",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Baluchistan",
        capital: "Baluchistan",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Mushasha",
        capital: "Mushasha",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Bengal",
        capital: "Bengal",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Vijayanagar",
        capital: "Deccan",
        taxValue: 3,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Delhi",
        capital: "Delhi",
        taxValue: 4,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Fars",
        capital: "Fars",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Gujarat",
        capital: "Gujarat",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Timurids",
        capital: "Herat",
        taxValue: 3,
        vassalsTaxValue: 2,
        vassals: ['Hejaz', 'Samarkand'],
    },{
        name: "Hormuz",
        capital: "Hormuz",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Ajam",
        capital: "Isfahan",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Najd",
        capital: "Najd",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Transoxiana",
        capital: "Samarkand",
        taxValue: 3,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Yemen",
        capital: "Yemen",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Pasai",
        capital: "Aceh",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Ming",
        capital: "Beijing",
        taxValue: 10,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Brunei",
        capital: "Brunei",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Ava",
        capital: "Burma",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Japan",
        capital: "Honshu",
        taxValue: 3,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Majapahit",
        capital: "Java",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Korea",
        capital: "Korea",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Malacca",
        capital: "Malacca",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Ayutthaya",
        capital: "Siam",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },{
        name: "Chagatai",
        capital: "Chagatai",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Manchu",
        capital: "Manchu",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Nogai",
        capital: "Nogai",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Oirat",
        capital: "Oirat",
        taxValue: 2,
        vassalsTaxValue: 2,
        vassals: ['Mongolia'],
    },
    {
        name: "Uzbek",
        capital: "Tyumen",
        taxValue: 4,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Kazan",
        capital: "Kazan",
        taxValue: 3,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Naxos",
        capital: "Naxos",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Yaroslavl",
        capital: "Yaroslavl",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Crimea",
        capital: "Crimea",
        taxValue: 4,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Livonian Order",
        capital: "Livland",
        taxValue: 3,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Riga",
        capital: "Riga",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Athens",
        capital: "Athens",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Lithuania",
        capital: "Vilnius",
        taxValue: 12,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Byzanthium",
        capital: "Constantinople",
        taxValue: 3,
        vassalsTaxValue: 1,
        vassals: ['Athina'],
    },
    {
        name: "Mazovia",
        capital: "Warszawa",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Moldavia",
        capital: "Suceava",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Muskovy",
        capital: "Moskva",
        taxValue: 10,
        vassalsTaxValue: 3,
        vassals: ['Pskov', 'Perm', 'Beloozero', ],
    },
    {
        name: "Odoyev",
        capital: "Odoyev",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Ryazan",
        capital: "Ryazan",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Tver",
        capital: "Tver",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Novgorod",
        capital: "Novgorod",
        taxValue: 7,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Pskov",
        capital: "Pskov",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Perm",
        capital: "Perm",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Beloozero",
        capital: "Beloozero",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Great Horde",
        capital: "Saratov",
        taxValue: 7,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Albania",
        capital: "Albania",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Serbia",
        capital: "Smederevo",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Wallachia",
        capital: "Tirgoviste",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Nogai",
        capital: "Nogai",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Shirvan",
        capital: "Shirvan",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Circassia",
        capital: "Circassia",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Imereti",
        capital: "Imereti",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Cyprus",
        capital: "Cyprus",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Karaman",
        capital: "Karaman",
        taxValue: 2,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Ramazan",
        capital: "Adana",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Aq Qoyunlu",
        capital: "Mush",
        taxValue: 3,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Bitlis",
        capital: "Bitlis",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    },
    {
        name: "Qara Qoyunlu",
        capital: "Tabriz",
        taxValue: 7,
        vassalsTaxValue: 1,
        vassals: ['Bitlis'],
    },
    {
        name: "Candar",
        capital: "Kastamonu",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    }, {
        name: "Trebizond",
        capital: "Trebizond",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    }, {
        name: "Georgia",
        capital: "Tbilisi",
        taxValue: 1,
        vassalsTaxValue: 0,
        vassals: [],
    }
]