import { NameIndex } from "./types";

export const nameIndexes: NameIndex[] = [
  { name: "Aberdeen", type: "province" },
  { name: "Abo", type: "province" },
  { name: "Aceh", type: "province" },
  { name: "Adal", type: "province" },
  { name: "Adana", type: "province" },
  { name: "Ajuuraan", type: "province" },
  { name: "Akershus", type: "province" },
  { name: "Albania", type: "province" },
  { name: "Al-quds", type: "province" },
  { name: "Altmark", type: "province" },
  { name: "Amasya", type: "province" },
  { name: "Amazonas", type: "province" },
  { name: "Amsterdam", type: "province" },
  { name: "Ancona", type: "province" },
  { name: "Angola", type: "province" },
  { name: "Anjou", type: "province" },
  { name: "Ankara", type: "province" },
  { name: "Antilles", type: "province" },
  { name: "Antwerpen", type: "province" },
  { name: "Arkhangelsk", type: "province" },
  { name: "Armagnac", type: "province" },
  { name: "Artois", type: "province" },
  { name: "Astrakhan", type: "province" },
  { name: "Athina", type: "province" },
  { name: "Augsburg", type: "province" },
  { name: "Avignon", type: "province" },
  { name: "Ayrshire", type: "province" },
  { name: "Azov", type: "province" },
  { name: "Badajoz", type: "province" },
  { name: "Baghdad", type: "province" },
  { name: "Bahia", type: "province" },
  { name: "Baleares", type: "province" },
  { name: "Balkh", type: "province" },
  { name: "Baluchistan", type: "province" },
  { name: "Bangazi", type: "province" },
  { name: "Barcelona", type: "province" },
  { name: "Bari", type: "province" },
  { name: "Basarabia", type: "province" },
  { name: "Basra", type: "province" },
  { name: "Beijing", type: "province" },
  { name: "Beira", type: "province" },
  { name: "Boloozero", type: "province" },
  { name: "Bengal", type: "province" },
  { name: "Benin", type: "province" },
  { name: "Beograd", type: "province" },
  { name: "Bergenhus", type: "province" },
  { name: "Bergslagen", type: "province" },
  { name: "Berlin", type: "province" },
  { name: "Bern", type: "province" },
  { name: "Berry", type: "province" },
  { name: "Bitlis", type: "province" },
  { name: "Bizerte", type: "province" },
  { name: "Bordeaux", type: "province" },
  { name: "Borgarsysla", type: "province" },
  { name: "Bosnia", type: "province" },
  { name: "Bourbon", type: "province" },
  { name: "Bourgogne", type: "province" },
  { name: "Braunschweig", type: "province" },
  { name: "Breda", type: "province" },
  { name: "Bremen", type: "province" },
  { name: "Brescia", type: "province" },
  { name: "Brugge", type: "province" },
  { name: "Brunei", type: "province" },
  { name: "Budejovice", type: "province" },
  { name: "Burgos", type: "province" },
  { name: "Burma", type: "province" },
  { name: "Buzau", type: "province" },
  { name: "Caffa", type: "province" },
  { name: "California", type: "province" },
  { name: "Canada", type: "province" },
  { name: "Canarias", type: "province" },
  { name: "Canton", type: "province" },
  { name: "Cape of Good Hope", type: "province" },
  { name: "Caux", type: "province" },
  { name: "Central Africa", type: "province" },
  { name: "Central America", type: "province" },
  { name: "Cernigovas", type: "province" },
  { name: "Ceuta", type: "province" },
  { name: "Chagati", type: "province" },
  { name: "Champagne", type: "province" },
  { name: "Charcas", type: "province" },
  { name: "Chengdu", type: "province" },
  { name: "Chile", type: "province" },
  { name: "Circassia", type: "province" },
  { name: "Constantinople", type: "province" },
  { name: "Cordoba", type: "province" },
  { name: "Coromandel", type: "province" },
  { name: "Corsica", type: "province" },
  { name: "Creta", type: "province" },
  { name: "Crimea", type: "province" },
  { name: "Cuzco", type: "province" },
  { name: "Cyprus", type: "province" },
  { name: "Danzig", type: "province" },
  { name: "Deccan", type: "province" },
  { name: "Delhi", type: "province" },
  { name: "Dimashq", type: "province" },
  { name: "Doab", type: "province" },
  { name: "Don", type: "province" },
  { name: "Dresden", type: "province" },
  { name: "Dumyat", type: "province" },
  { name: "Eatern Australia", type: "province" },
  { name: "East Siberia", type: "province" },
  { name: "Edirne", type: "province" },
  { name: "Edisanas", type: "province" },
  { name: "Erzurum", type: "province" },
  { name: "Essex", type: "province" },
  { name: "Ethiopia", type: "province" },
  { name: "Fars", type: "province" },
  { name: "Fayyum (1444)", type: "province" },
  { name: "Ferrara", type: "province" },
  { name: "Fez", type: "province" },
  { name: "Firenze", type: "province" },
  { name: "Florida", type: "province" },
  { name: "Franche Comte", type: "province" },
  { name: "Frankfurt", type: "province" },
  { name: "Friesland", type: "province" },
  { name: "Furdan", type: "province" },
  { name: "Galich", type: "province" },
  { name: "Galicia", type: "province" },
  { name: "Gazzah", type: "province" },
  { name: "Gelre", type: "province" },
  { name: "Genova", type: "province" },
  { name: "Geneve", type: "province" },
  { name: "Gent", type: "province" },
  { name: "Gharb", type: "province" },
  { name: "Gibraltar", type: "province" },
  { name: "Goa", type: "province" },
  { name: "Gold Coast", type: "province" },
  { name: "Goldingen", type: "province" },
  { name: "Gotland", type: "province" },
  { name: "Granada", type: "province" },
  { name: "Great Lakes", type: "province" },
  { name: "Great Plains", type: "province" },
  { name: "Gujarat", type: "province" },
  { name: "Guria", type: "province" },
  { name: "Guyana", type: "province" },
  { name: "Halab", type: "province" },
  { name: "Halsingland", type: "province" },
  { name: "Hamburg", type: "province" },
  { name: "Hangzhou", type: "province" },
  { name: "Hannover", type: "province" },
  { name: "Herat", type: "province" },
  { name: "Hejaz", type: "province" },
  { name: "Holstein", type: "province" },
  { name: "Honshu", type: "province" },
  { name: "Hormuz", type: "province" },
  { name: "Hudavendigar", type: "province" },
  { name: "Hudson Bay", type: "province" },
  { name: "Hum", type: "province" },
  { name: "Hunyad", type: "province" },
  { name: "Imereti", type: "province" },
  { name: "Isfahan", type: "province" },
  { name: "Iskandariyya", type: "province" },
  { name: "Izmir", type: "province" },
  { name: "Jaffa", type: "province" },
  { name: "Java", type: "province" },
  { name: "Kabylia", type: "province" },
  { name: "Kalisz", type: "province" },
  { name: "Karaman", type: "province" },
  { name: "Kargopol", type: "province" },
  { name: "Karnten", type: "province" },
  { name: "Kasimov", type: "province" },
  { name: "Kastamonu", type: "province" },
  { name: "Katsina", type: "province" },
  { name: "Kaunas", type: "province" },
  { name: "Kazakhstan", type: "province" },
  { name: "Kazan", type: "province" },
  { name: "Khiva", type: "province" },
  { name: "Kijevas", type: "province" },
  { name: "Kilwa", type: "province" },
  { name: "Kirkuk", type: "province" },
  { name: "Kleve", type: "province" },
  { name: "Kobenhavn", type: "province" },
  { name: "Koln", type: "province" },
  { name: "Kongo", type: "province" },
  { name: "Konisberg", type: "province" },
  { name: "Konya", type: "province" },
  { name: "Korea", type: "province" },
  { name: "Koslin", type: "province" },
  { name: "Kosovo", type: "province" },
  { name: "Krain", type: "province" },
  { name: "Krakow", type: "province" },
  { name: "Kulm", type: "province" },
  { name: "Kutahya", type: "province" },
  { name: "Kyushu", type: "province" },
  { name: "Kyzy-Yar", type: "province" },
  { name: "Ladoga", type: "province" },
  { name: "Laighin", type: "province" },
  { name: "Lancashire", type: "province" },
  { name: "Landshut", type: "province" },
  { name: "La Plata", type: "province" },
  { name: "Leipzig", type: "province" },
  { name: "Liege", type: "province" },
  { name: "Lienz", type: "province" },
  { name: "Limousin", type: "province" },
  { name: "Lisboa", type: "province" },
  { name: "Livland", type: "province" },
  { name: "Lorraine", type: "province" },
  { name: "London", type: "province" },
  { name: "Lothian", type: "province" },
  { name: "Lubeck", type: "province" },
  { name: "Lublin", type: "province" },
  { name: "Luxembourg", type: "province" },
  { name: "Lwow", type: "province" },
  { name: "Lyon", type: "province" },
  { name: "Madagascar", type: "province" },
  { name: "Madeira", type: "province" },
  { name: "Madrid", type: "province" },
  { name: "Magdeburg", type: "province" },
  { name: "Maine", type: "province" },
  { name: "Mainz", type: "province" },
  { name: "Majar", type: "province" },
  { name: "Malacca", type: "province" },
  { name: "Mali", type: "province" },
  { name: "Malta", type: "province" },
  { name: "Manchu", type: "province" },
  { name: "Mantova", type: "province" },
  { name: "Marienburg", type: "province" },
  { name: "Mentese", type: "province" },
  { name: "Marrakech", type: "province" },
  { name: "Mecklenburg", type: "province" },
  { name: "Mesina", type: "province" },
  { name: "Mexico", type: "province" },
  { name: "Mhumhain", type: "province" },
  { name: "Milano", type: "province" },
  { name: "Minas Gerais", type: "province" },
  { name: "Minskas", type: "province" },
  { name: "Mississippi", type: "province" },
  { name: "Mitidja", type: "province" },
  { name: "Moluccas", type: "province" },
  { name: "Mongolia", type: "province" },
  { name: "Montpellier", type: "province" },
  { name: "Morea", type: "province" },
  { name: "Moskva", type: "province" },
  { name: "Mosul", type: "province" },
  { name: "Munchen", type: "province" },
  { name: "Munster", type: "province" },
  { name: "Murcia", type: "province" },
  { name: "Murom", type: "province" },
  { name: "Mush", type: "province" },
  { name: "Mutapa", type: "province" },
  { name: "Najd", type: "province" },
  { name: "Namur", type: "province" },
  { name: "Nantes", type: "province" },
  { name: "Napoli", type: "province" },
  { name: "Natal", type: "province" },
  { name: "Naugardukas", type: "province" },
  { name: "Navarra", type: "province" },
  { name: "Naxos", type: "province" },
  { name: "Neumark", type: "province" },
  { name: "Neva", type: "province" },
  { name: "New England", type: "province" },
  { name: "New Granada", type: "province" },
  { name: "Nizhny Novgorod", type: "province" },
  { name: "Nogai", type: "province" },
  { name: "Normandie", type: "province" },
  { name: "Northumberland", type: "province" },
  { name: "Novgorod", type: "province" },
  { name: "Nurnberg", type: "province" },
  { name: "Nyland", type: "province" },
  { name: "Odoyev", type: "province" },
  { name: "Oirat", type: "province" },
  { name: "Okhotsk", type: "province" },
  { name: "Olomouc", type: "province" },
  { name: "Olonets", type: "province" },
  { name: "Oran", type: "province" },
  { name: "Orleans", type: "province" },
  { name: "Osterbotten", type: "province" },
  { name: "Ostergotland", type: "province" },
  { name: "Osterreich", type: "province" },
  { name: "Ostylland", type: "province" },
  { name: "Oxford", type: "province" },
  { name: "Paris", type: "province" },
  { name: "Pale", type: "province" },
  { name: "Palermo", type: "province" },
  { name: "Papua", type: "province" },
  { name: "Parma", type: "province" },
  { name: "Perm", type: "province" },
  { name: "Pernambuco", type: "province" },
  { name: "Perth", type: "province" },
  { name: "Pest", type: "province" },
  { name: "Pfalz", type: "province" },
  { name: "Philippines", type: "province" },
  { name: "Picardie", type: "province" },
  { name: "Piemonte", type: "province" },
  { name: "Pisa", type: "province" },
  { name: "Podole", type: "province" },
  { name: "Poitou", type: "province" },
  { name: "Polockas", type: "province" },
  { name: "Poltava", type: "province" },
  { name: "Porto", type: "province" },
  { name: "Postdam", type: "province" },
  { name: "Poznan", type: "province" },
  { name: "Pozsony", type: "province" },
  { name: "Praha", type: "province" },
  { name: "Provence", type: "province" },
  { name: "Pskov", type: "province" },
  { name: "Qafsah", type: "province" },
  { name: "Qahirah", type: "province" },
  { name: "Quito", type: "province" },
  { name: "Ragusa", type: "province" },
  { name: "Ragensburg", type: "province" },
  { name: "Rennes", type: "province" },
  { name: "Reval", type: "province" },
  { name: "Rhodes", type: "province" },
  { name: "Riga", type: "province" },
  { name: "Rijeka", type: "province" },
  { name: "Rio de Janeiro", type: "province" },
  { name: "Roma", type: "province" },
  { name: "Rudohori", type: "province" },
  { name: "Ryazan", type: "province" },
  { name: "Rzkhev", type: "province" },
  { name: "Saintonge", type: "province" },
  { name: "Salamanca", type: "province" },
  { name: "Salerno", type: "province" },
  { name: "Salzburg", type: "province" },
  { name: "Samarkand", type: "province" },
  { name: "Sandomierz", type: "province" },
  { name: "Sarai", type: "province" },
  { name: "Saratov", type: "province" },
  { name: "Sardenya", type: "province" },
  { name: "Savoie", type: "province" },
  { name: "Selanik", type: "province" },
  { name: "Sevilla", type: "province" },
  { name: "Shirvan", type: "province" },
  { name: "Shrewsbury", type: "province" },
  { name: "Siam", type: "province" },
  { name: "Siena", type: "province" },
  { name: "Sieradz", type: "province" },
  { name: "Silesia", type: "province" },
  { name: "Silistre", type: "province" },
  { name: "Sivas", type: "province" },
  { name: "Slesvig", type: "province" },
  { name: "Smederevo", type: "province" },
  { name: "Smolenskas", type: "province" },
  { name: "Sofya", type: "province" },
  { name: "Songhai", type: "province" },
  { name: "Sopron", type: "province" },
  { name: "Sousse", type: "province" },
  { name: "Southern Australia", type: "province" },
  { name: "South Sumatra", type: "province" },
  { name: "St. Gallen", type: "province" },
  { name: "Steiermark", type: "province" },
  { name: "Stettin", type: "province" },
  { name: "Stockholm", type: "province" },
  { name: "Stralsund", type: "province" },
  { name: "Suceava", type: "province" },
  { name: "Sungdau", type: "province" },
  { name: "Sus", type: "province" },
  { name: "Suzdal", type: "province" },
  { name: "Szabolcs", type: "province" },
  { name: "Szepes", type: "province" },
  { name: "Tabriz", type: "province" },
  { name: "Tafilalt", type: "province" },
  { name: "Tambov", type: "province" },
  { name: "Talgiers", type: "province" },
  { name: "Tarabulus", type: "province" },
  { name: "Tblisi", type: "province" },
  { name: "Teke", type: "province" },
  { name: "Terek", type: "province" },
  { name: "Tikrit", type: "province" },
  { name: "Timbuktu", type: "province" },
  { name: "Timor", type: "province" },
  { name: "Tirgoviste", type: "province" },
  { name: "Tirol", type: "province" },
  { name: "Tlemcen", type: "province" },
  { name: "Torda", type: "province" },
  { name: "Toulouse", type: "province" },
  { name: "Trebizond", type: "province" },
  { name: "Treviso", type: "province" },
  { name: "Trier", type: "province" },
  { name: "Tripoli", type: "province" },
  { name: "Trondheim", type: "province" },
  { name: "Tunis", type: "province" },
  { name: "Tver", type: "province" },
  { name: "Tyumen", type: "province" },
  { name: "Ulaidh", type: "province" },
  { name: "Ulm", type: "province" },
  { name: "Upper Egypt", type: "province" },
  { name: "Ural", type: "province" },
  { name: "Urfa", type: "province" },
  { name: "Valencia", type: "province" },
  { name: "Verona", type: "province" },
  { name: "Vestjylland", type: "province" },
  { name: "Viatka", type: "province" },
  { name: "Vilnius", type: "province" },
  { name: "Virginia", type: "province" },
  { name: "Vladmir", type: "province" },
  { name: "Vogelkop", type: "province" },
  { name: "Vologda", type: "province" },
  { name: "Voluine", type: "province" },
  { name: "Wales", type: "province" },
  { name: "Warszawa", type: "province" },
  { name: "Wessex", type: "province" },
  { name: "Western Australia", type: "province" },
  { name: "West Siberia", type: "province" },
  { name: "Wien", type: "province" },
  { name: "Wittenberg", type: "province" },
  { name: "Xian", type: "province" },
  { name: "Yanya", type: "province" },
  { name: "Yarkland", type: "province" },
  { name: "Yaroslavl", type: "province" },
  { name: "Yedi-Shkul", type: "province" },
  { name: "Yemen", type: "province" },
  { name: "Yeravan", type: "province" },
  { name: "Zagreb", type: "province" },
  { name: "Zaporze", type: "province" },
  { name: "Zara", type: "province" },
  { name: "Zaragoza", type: "province" },
  { name: "Zeeland", type: "province" },
  { name: "Zemaitija", type: "province" },
  { name: "Beloozero", type: "province" },
  { name: "England", type: "kingdom" },
  { name: "Aragon", type: "kingdom" },
  { name: "Brittany", type: "kingdom" },
  { name: "Castile", type: "kingdom" },
  { name: "Desmond", type: "kingdom" },
  { name: "Leinster", type: "kingdom" },
  { name: "Tyrone", type: "kingdom" },
  { name: "Portugal", type: "kingdom" },
  { name: "Scotland", type: "kingdom" },
  { name: "France", type: "kingdom" },
  { name: "Denmark", type: "kingdom" },
  { name: "Sweden", type: "kingdom" },
  { name: "Norway", type: "kingdom" },
  { name: "Morroco", type: "kingdom" },
  { name: "Djerid", type: "kingdom" },
  { name: "Bavaria", type: "kingdom" },
  { name: "Bohemia", type: "kingdom" },
  { name: "Brandenburg", type: "kingdom" },
  { name: "Burgundy", type: "kingdom" },
  { name: "Savoy", type: "kingdom" },
  { name: "Brabant", type: "kingdom" },
  { name: "Flanders", type: "kingdom" },
  { name: "Brunswick", type: "kingdom" },
  { name: "Holland", type: "kingdom" },
  { name: "Pomerania", type: "kingdom" },
  { name: "The Palatinate", type: "kingdom" },
  { name: "Nuremberg", type: "kingdom" },
  { name: "Saxony", type: "kingdom" },
  { name: "Cleves", type: "kingdom" },
  { name: "Cologne", type: "kingdom" },
  { name: "Austria", type: "kingdom" },
  { name: "Florence", type: "kingdom" },
  { name: "Papal States", type: "kingdom" },
  { name: "Genoa", type: "kingdom" },
  { name: "Mantua", type: "kingdom" },
  { name: "Milan", type: "kingdom" },
  { name: "Naples", type: "kingdom" },
  { name: "Switzerland", type: "kingdom" },
  { name: "Venice", type: "kingdom" },
  { name: "Knights", type: "kingdom" },
  { name: "Hungary", type: "kingdom" },
  { name: "Croatia", type: "kingdom" },
  { name: "Poland", type: "kingdom" },
  { name: "Ottomans", type: "kingdom" },
  { name: "Teutonic Order", type: "kingdom" },
  { name: "Aztec", type: "kingdom" },
  { name: "Inca", type: "kingdom" },
  { name: "Mamluks", type: "kingdom" },
  { name: "Mushasha", type: "kingdom" },
  { name: "Vijayanagar", type: "kingdom" },
  { name: "Timurids", type: "kingdom" },
  { name: "Ajam", type: "kingdom" },
  { name: "Transoxiana", type: "kingdom" },
  { name: "Pasai", type: "kingdom" },
  { name: "Ming", type: "kingdom" },
  { name: "Ava", type: "kingdom" },
  { name: "Japan", type: "kingdom" },
  { name: "Majapahit", type: "kingdom" },
  { name: "Ayutthaya", type: "kingdom" },
  { name: "Chagatai", type: "kingdom" },
  { name: "Uzbek", type: "kingdom" },
  { name: "Livonian Order", type: "kingdom" },
  { name: "Athens", type: "kingdom" },
  { name: "Lithuania", type: "kingdom" },
  { name: "Byzanthium", type: "kingdom" },
  { name: "Mazovia", type: "kingdom" },
  { name: "Moldavia", type: "kingdom" },
  { name: "Muskovy", type: "kingdom" },
  { name: "Great Horde", type: "kingdom" },
  { name: "Serbia", type: "kingdom" },
  { name: "Wallachia", type: "kingdom" },
  { name: "Ramazan", type: "kingdom" },
  { name: "Aq Qoyunlu", type: "kingdom" },
  { name: "Qara Qoyunlu", type: "kingdom" },
  { name: "Candar", type: "kingdom" },
  { name: "Georgia", type: "kingdom" },
  { name: "Aegean Archipelago", type: "area" },
  { name: "Africa", type: "area" },
  { name: "Algiers", type: "area" },
  { name: "America", type: "area" },
  { name: "Andalucia", type: "area" },
  { name: "Aquitaine", type: "area" },
  { name: "Armenia", type: "area" },
  { name: "Aydin", type: "area" },
  { name: "Bavaria Swabia", type: "area" },
  { name: "Brittany Normandy", type: "area" },
  { name: "Caucasus", type: "area" },
  { name: "Central Italy", type: "area" },
  { name: "Central Russia", type: "area" },
  { name: "Corsica Sardinia", type: "area" },
  { name: "Croatia Bosnia", type: "area" },
  { name: "Cyrenaica", type: "area" },
  { name: "Dalmatia", type: "area" },
  { name: "East Anglia", type: "area" },
  { name: "Eastern Ukraine", type: "area" },
  { name: "Egypt", type: "area" },
  { name: "Estonia Livonia", type: "area" },
  { name: "Far east", type: "area" },
  { name: "Finland", type: "area" },
  { name: "Flanders Wallonia", type: "area" },
  { name: "Gotaland Skane", type: "area" },
  { name: "Greece", type: "area" },
  { name: "Hungarian Plain", type: "area" },
  { name: "India Arabia", type: "area" },
  { name: "Iraq", type: "area" },
  { name: "Ireland", type: "area" },
  { name: "Jutland", type: "area" },
  { name: "Karelia", type: "area" },
  { name: "Kurdistan", type: "area" },
  { name: "Languedoc", type: "area" },
  { name: "Leon", type: "area" },
  { name: "Loire", type: "area" },
  { name: "Lombardy", type: "area" },
  { name: "Lower Saxony", type: "area" },
  { name: "Macaronesia", type: "area" },
  { name: "Macedonia Thrace", type: "area" },
  { name: "Mazovia Malopolska", type: "area" },
  { name: "Moscow Ryazan", type: "area" },
  { name: "Netherlands", type: "area" },
  { name: "Norrland", type: "area" },
  { name: "North America", type: "area" },
  { name: "North Sahara", type: "area" },
  { name: "Northen Central Asia", type: "area" },
  { name: "Northern Anatolia", type: "area" },
  { name: "Northern Central Asia", type: "area" },
  { name: "Northern Marroco", type: "area" },
  { name: "Northumbria", type: "area" },
  { name: "Ostlandet", type: "area" },
  { name: "Ostrobothnia", type: "area" },
  { name: "Palestine", type: "area" },
  { name: "Pomorye", type: "area" },
  { name: "Prussia", type: "area" },
  { name: "Red Ruthenia", type: "area" },
  { name: "Rhineland", type: "area" },
  { name: "Royal Hungary", type: "area" },
  { name: "Rum", type: "area" },
  { name: "Seine", type: "area" },
  { name: "Serbia Albania", type: "area" },
  { name: "Sicily", type: "area" },
  { name: "Sjaelland Fyn", type: "area" },
  { name: "Suthern Marroco", type: "area" },
  { name: "Svealand", type: "area" },
  { name: "Syria", type: "area" },
  { name: "Transylvania", type: "area" },
  { name: "Tripolitania", type: "area" },
  { name: "Trondelag", type: "area" },
  { name: "Tunisia", type: "area" },
  { name: "Venetia", type: "area" },
  { name: "Vestlandet", type: "area" },
  { name: "Wales Essex", type: "area" },
  { name: "Wallachia Bulgaria", type: "area" },
  { name: "Western Ukraine", type: "area" },
  { name: "Westphalia", type: "area" },
  { name: "White Ruthenia", type: "area" },
  { name: "Wielkopolska", type: "area" },
  { name: "North Sea", type: "node" },
  { name: "Baltic Sea", type: "node" },
  { name: "English Channel", type: "node" },
  { name: "Eastern Atlantic", type: "node" },
  { name: "Gulf of Lion", type: "node" },
  { name: "Central Mediterranean", type: "node" },
  { name: "Adriatic Sea", type: "node" },
  { name: "Aegean Sea", type: "node" },
  { name: "Black Sea", type: "node" },
  { name: "Eastern Mediterranean", type: "node" },
  { name: "Red Sea", type: "node" },
  { name: "Persian Gulf", type: "node" },
  { name: "Indian Ocean", type: "node" },
  { name: "China & Japan", type: "node" },
  { name: "East Indies", type: "node" },
  { name: "Caribbean Sea", type: "node" },
  { name: "South Western Atlantic", type: "node" },
  { name: "Eastern Pacific", type: "node" },
  { name: "South America", type: "node" },
  { name: "Southeastern Atlantic", type: "node" },
  { name: "East African Coast", type: "node" },
  { name: "Siberia", type: "node" },
  { name: "Obkhotsk", type: "node" }
];
