import { TradeNode } from "./types";

export const nodes: TradeNode[] = [
  {
    name: "North Sea",
    distant: false,
    top: 6.9,
    left: 30.8,
    maritime: true,
  },
  {
    name: "Lubeck",
    distant: false,
    top: 15.4,
    left: 63.3,
    maritime: true,
  },
  {
    name: "Kazan",
    distant: false,
    top: 32.8,
    left: 96.5,
    maritime: false,
  },
  {
    name: "Champagne",
    distant: false,
    top: 48.85,
    left: 36.75,
    maritime: false,
  },
  {
    name: "Novogorod",
    distant: false,
    top: 19.9,
    left: 76.1,
    maritime: false,
  },
  {
    name: "Kiev",
    distant: false,
    top: 42.2,
    left: 74.6,
    maritime: false,
  },
  {
    name: "Saxony",
    distant: false,
    top: 42.6,
    left: 47.5,
    maritime: false,
  },
  {
    name: "Sevilla",
    distant: false,
    top: 83.1,
    left: 19.4,
    maritime: true,
  },
  {
    name: "Magreb",
    distant: false,
    top: 93.1,
    left: 33.3, 
    maritime: false,
  },
  {
    name: "Krakow",
    distant: false,
    top: 41.1,
    left: 63.4,
    maritime: false,
  },
  {
    name: "Alexandria",
    distant: false,
    top: 85.9,
    left: 74.4,
    maritime: true,
  },
  {
    name: "Astrakhan",
    distant: false,
    top: 56.05,
    left: 96.45, 
    maritime: false,
  },
  {
    name: "Baltic Sea",
    distant: false,
    top: 15.4,
    left: 63.25,
    maritime: true,
  },
  {
    name: "English Channel",
    distant: false,
    top: 32.6,
    left: 35.8,
    maritime: true,
  },
  {
    name: "Bordeaux",
    distant: false,
    top: 56.1,
    left: 19.4,
    maritime: true,
  },
  {
    name: "Genoa",
    distant: false,
    top: 72.4,
    left: 41.7,
    maritime: true,
  },

  {
    name: "Black Sea",
    distant: false,
    top: 65.6,
    left: 76.8,
    maritime: true,
  },
  {
    name: "Indian Ocean",
    distant: true,
    top: 64.2,
    left: 3.0,
    maritime: true,
  },
  {
    name: "China Japan",
    distant: true,
    top: 78.3,
    left: 7.5,
    maritime: true,
  },
  {
    name: "East Indies",
    distant: true,
    top: 88.6,
    left: 2.1,
    maritime: true,
  },
  {
    name: "North America",
    distant: true,
    top: 6.7,
    left: 8.3,
    maritime: true,
  },
  {
    name: "Wien",
    distant: true,
    top: 49.3,
    left: 54.2,
    maritime: false,
  },
  {
    name: "South America",
    distant: true,
    top: 23.9,
    left: 2.5,  
    maritime: true,
  },
  {
    name: "Ivory Coast",
    distant: true,
    top: 47.8,
    left: 2.2,
    maritime: true,
  },
  {
    name: "Aleppo",
    distant: false,
    top: 86.1,
    left: 87.8,
    maritime: false,
  },
];