import { Province } from "./types";

export const provinces: Province[] = [
  {
    name: "Aberdeen",
    type: "city",
    top: "17.4",
    left: "27.6",
    size: "small",
    kingdomCaptial: "Lothian",
    map: "main",
    area: "Scotland",
    port: true,
  },
  {
    name: "Abo",
    type: "city",
    top: "11.4",
    left: "64.8",
    size: "small",
    kingdomCaptial: "Stockholm",
    map: "expansion",
    area: "Finland",
    port: true,
  },
  {
    name: "Aceh",
    type: "city",
    top: "82.8",
    left: "0.58",
    size: "small",
    kingdomCaptial: "Aceh",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "Adal",
    type: "city",
    top: "36.8",
    left: "9.9",
    size: "small",
    kingdomCaptial: "Adal",
    map: "distant",
    area: "Africa",
    port: true,
  },
  {
    name: "Adana",
    type: "city",
    top: "80.6",
    left: "83.2",
    size: "small",
    kingdomCaptial: "Adana",
    map: "expansion",
    area: "Karaman",
    port: true,
  },
  {
    name: "Ajuuraan",
    type: "city",
    top: "39.3",
    left: "9.8",
    size: "small",
    kingdomCaptial: "Ajuuraan",
    map: "distant",
    area: "Africa",
    port: true,
  },
  {
    name: "Akershus",
    type: "city",
    top: "11.28",
    left: "50.3",
    size: "small",
    kingdomCaptial: "Akershus",
    map: "main",
    area: "Ostlandet",
    port: true,
  },
  {
    name: "Albania",
    type: "city",
    top: "71.7",
    left: "63",
    size: "small",
    kingdomCaptial: "Albania",
    map: "expansion",
    area: "Serbia Albania",
    port: true,
  },
  {
    name: "Al-quds",
    type: "city",
    top: "93.3",
    left: "83",
    size: "small",
    kingdomCaptial: "Qahirah",
    map: "expansion",
    area: "Palestine",
    port: false,
  },
  {
    name: "Altmark",
    type: "city",
    top: "34",
    left: "50.8",
    size: "small",
    kingdomCaptial: "Berlin",
    map: "main",
    area: "Brandenburg",
    port: false,
  },
  {
    name: "Amasya",
    type: "city",
    top: "71",
    left: "84.1",
    size: "small",
    kingdomCaptial: "Edirne",
    map: "expansion",
    area: "Rum",
    port: false,
  },
  {
    name: "Amazonas",
    type: "territory",
    top: "17.1",
    left: "7.1",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: false,
  },
  {
    name: "Amsterdam",
    type: "city",
    top: "34.1",
    left: "39.6",
    size: "small",
    kingdomCaptial: "Amsterdam",
    map: "main",
    area: "Netherlands",
    port: true,
  },
  {
    name: "Ancona",
    type: "city",
    top: "66.3",
    left: "53.5",
    size: "small",
    kingdomCaptial: "Roma",
    map: "main",
    area: "Central Italy",
    port: true,
  },
  {
    name: "Angola",
    type: "territory",
    top: "44.6",
    left: "4.8",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "Africa",
    port: false,
  },
  {
    name: "Anjou",
    type: "city",
    top: "52.4",
    left: "31.55",
    size: "small",
    kingdomCaptial: "Provence",
    map: "main",
    area: "Aquitaine",
    port: false,
  },
  {
    name: "Ankara",
    type: "city",
    top: "73.6",
    left: "79.5",
    size: "small",
    kingdomCaptial: "Edirne",
    map: "expansion",
    area: "Northern Anatolia",
    port: false,
  },
  {
    name: "Antilles",
    type: "territory",
    top: "10.9",
    left: "5.3",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Antwerpen",
    type: "city",
    top: "39.1",
    left: "39.6",
    size: "small",
    kingdomCaptial: "Antwerpen",
    map: "main",
    area: "Flanders Wallonia",
    port: true,
  },
  {
    name: "Arkhangelsk",
    type: "city",
    top: "4.4",
    left: "80.4",
    size: "small",
    kingdomCaptial: "Novgorod",
    map: "expansion",
    area: "Pomorye",
    port: true,
  },
  {
    name: "Armagnac",
    type: "city",
    top: "63",
    left: "31.95",
    size: "small",
    kingdomCaptial: "Paris",
    map: "main",
    area: "Aquitaine",
    port: false,
  },
  {
    name: "Artois",
    type: "city",
    top: "42.4",
    left: "36.05",
    size: "small",
    kingdomCaptial: "Bourgogne",
    map: "main",
    area: "Seine",
    port: false,
  },
  {
    name: "Astrakhan",
    type: "city",
    top: "53",
    left: "97.48",
    size: "small",
    kingdomCaptial: "Saratov",
    map: "expansion",
    area: "Astrakhan",
    port: false,
  },
  {
    name: "Athina",
    type: "city",
    top: "79.3",
    left: "68.9",
    size: "small",
    kingdomCaptial: "Athina",
    map: "expansion",
    area: "Greece",
    port: true,
  },
  {
    name: "Augsburg",
    type: "city",
    top: "49.9",
    left: "48.8",
    size: "small",
    kingdomCaptial: "Augsburg",
    map: "main",
    area: "Bavaria Swabia",
    port: false,
  },
  {
    name: "Avignon",
    type: "city",
    top: "61.05",
    left: "38.8",
    size: "small",
    kingdomCaptial: "Roma",
    map: "main",
    area: "Languedoc",
    port: false,
  },
  {
    name: "Ayrshire",
    type: "city",
    top: "23.6",
    left: "24.05",
    size: "small",
    kingdomCaptial: "Lothian",
    map: "main",
    area: "Scotland",
    port: true,
  },
  {
    name: "Azov",
    type: "city",
    top: "53.9",
    left: "88.45",
    size: "small",
    kingdomCaptial: "Crimea",
    map: "expansion",
    area: "Crimea",
    port: true,
  },
  {
    name: "Badajoz",
    type: "city",
    top: "76.4",
    left: "21.7",
    size: "small",
    kingdomCaptial: "Madrid",
    map: "main",
    area: "Leon",
    port: false,
  },
  {
    name: "Baghdad",
    type: "city",
    top: "86.9",
    left: "95.1",
    size: "small",
    kingdomCaptial: "Tabriz",
    map: "expansion",
    area: "Iraq",
    port: false,
  },
  {
    name: "Bahia",
    type: "territory",
    top: "19.1",
    left: "10.15",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Baleares",
    type: "city",
    top: "75.4",
    left: "36.7",
    size: "small",
    kingdomCaptial: "Valencia",
    map: "main",
    area: "Aragon",
    port: false,
  },
  {
    name: "Balkh",
    type: "city",
    top: "57",
    left: "5.4",
    size: "small",
    kingdomCaptial: "Herat",
    map: "distant",
    area: "India Arabia",
    port: false,
  },
  {
    name: "Baluchistan",
    type: "city",
    top: "59.8",
    left: "4.6",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "India Arabia",
    port: true,
  },
  {
    name: "Bangazi",
    type: "city",
    top: "90.8",
    left: "62.9",
    size: "small",
    kingdomCaptial: "Qahirah",
    map: "expansion",
    area: "Cyrenaica",
    port: true,
  },
  {
    name: "Barcelona",
    type: "city",
    top: "69.5",
    left: "35.7",
    size: "small",
    kingdomCaptial: "Valencia",
    map: "main",
    area: "Aragon",
    port: true,
  },
  {
    name: "Bari",
    type: "city",
    top: "72.8",
    left: "58.45",
    size: "small",
    kingdomCaptial: "Napoli",
    map: "main",
    area: "Naples",
    port: true,
  },
  {
    name: "Basarabia",
    type: "city",
    top: "58",
    left: "76",
    size: "small",
    kingdomCaptial: "Suceava",
    map: "expansion",
    area: "Moldavia",
    port: true,
  },
  {
    name: "Basra",
    type: "city",
    top: "57.6",
    left: "0.8",
    size: "small",
    kingdomCaptial: "Basra",
    map: "distant",
    area: "India Arabia",
    port: false,
  },
  {
    name: "Beijing",
    type: "city",
    top: "73.7",
    left: "3.9",
    size: "large",
    kingdomCaptial: "Beijing",
    map: "distant",
    area: "Far East",
    port: false,
  },
  {
    name: "Beira",
    type: "city",
    top: "72.2",
    left: "19.5",
    size: "small",
    kingdomCaptial: "Lisboa",
    map: "main",
    area: "Portugal",
    port: true,
  },
  {
    name: "Boloozero",
    type: "city",
    top: "14.6",
    left: "85",
    size: "small",
    kingdomCaptial: "Boloozero",
    map: "expansion",
    area: "Vologda",
    port: false,
  },
  {
    name: "Bengal",
    type: "city",
    top: "60.4",
    left: "9.8",
    size: "large",
    kingdomCaptial: "Bengal",
    map: "distant",
    area: "India Arabia",
    port: true,
  },
  {
    name: "Benin",
    type: "city",
    top: "38",
    left: "3.4",
    size: "small",
    kingdomCaptial: "Benin",
    map: "distant",
    area: "Africa",
    port: true,
  },
  {
    name: "Beograd",
    type: "city",
    top: "61.7",
    left: "63.9",
    size: "small",
    kingdomCaptial: "Pest",
    map: "main",
    area: "Serbia Albania",
    port: false,
  },
  {
    name: "Bergenhus",
    type: "city",
    top: "9.5",
    left: "43.5",
    size: "small",
    kingdomCaptial: "Akershus",
    map: "main",
    area: "Vestlandet",
    port: true,
  },
  {
    name: "Bergslagen",
    type: "city",
    top: "11.1",
    left: "55.9",
    size: "small",
    kingdomCaptial: "Stockholm",
    map: "main",
    area: "Svealand",
    port: false,
  },
  {
    name: "Berlin",
    type: "city",
    top: "34.1",
    left: "54.25",
    size: "small",
    kingdomCaptial: "Berlin",
    map: "main",
    area: "Brandenburg",
    port: false,
  },
  {
    name: "Bern",
    type: "city",
    top: "53.5",
    left: "44.1",
    size: "small",
    kingdomCaptial: "Bern",
    map: "main",
    area: "Switzerland",
    port: false,
  },
  {
    name: "Berry",
    type: "city",
    top: "53.15",
    left: "36.05",
    size: "small",
    kingdomCaptial: "Paris",
    map: "main",
    area: "Loire",
    port: false,
  },
  {
    name: "Bitlis",
    type: "city",
    top: "76.15",
    left: "92.7",
    size: "small",
    kingdomCaptial: "Bitlis",
    map: "expansion",
    area: "Kurdistan",
    only: 1444,
    port: false,
  },
  {
    name: "Bizerte",
    type: "city",
    top: "84.2",
    left: "45.95",
    size: "small",
    kingdomCaptial: "Tunis",
    map: "expansion",
    area: "Tunisia",
    port: true,
  },
  {
    name: "Bordeaux",
    type: "city",
    top: "57.7",
    left: "30.3",
    size: "large",
    kingdomCaptial: "London",
    map: "main",
    area: "Aquitaine",
    port: true,
  },
  {
    name: "Borgarsysla",
    type: "city",
    top: "14.2",
    left: "51.24",
    size: "small",
    kingdomCaptial: "Akershus",
    map: "main",
    area: "Ostlandet",
    port: true,
  },
  {
    name: "Bosnia",
    type: "city",
    top: "60.4",
    left: "60.25",
    size: "small",
    kingdomCaptial: "Bosnia",
    map: "main",
    area: "Croatia Bosnia",
    port: false,
  },
  {
    name: "Bourbon",
    type: "city",
    top: "55",
    left: "37.34",
    size: "small",
    kingdomCaptial: "Paris",
    map: "distant",
    area: "Loire",
    port: false,
  },
  {
    name: "Bourgogne",
    type: "city",
    top: "52.1",
    left: "39",
    size: "large",
    kingdomCaptial: "Bourgogne",
    map: "main",
    area: "Burgundy",
    port: false,
  },
  {
    name: "Braunschweig",
    type: "city",
    top: "39.2",
    left: "48.4",
    size: "small",
    kingdomCaptial: "Braunschweig",
    map: "main",
    area: "Lower Saxony",
    port: false,
  },
  {
    name: "Breda",
    type: "city",
    top: "36.9",
    left: "41.1",
    size: "small",
    kingdomCaptial: "Antwerpen",
    map: "main",
    area: "Netherlands",
    port: false,
  },
  {
    name: "Bremen",
    type: "city",
    top: "32.9",
    left: "45.8",
    size: "small",
    kingdomCaptial: "Bremen",
    map: "main",
    area: "Lower Saxony",
    port: true,
  },
  {
    name: "Brescia",
    type: "city",
    top: "58.1",
    left: "48.34",
    size: "small",
    kingdomCaptial: "Venezia",
    map: "main",
    area: "Lombardy",
    port: false,
  },
  {
    name: "Brugge",
    type: "city",
    top: "38.7",
    left: "36.65",
    size: "small",
    kingdomCaptial: "Brugge",
    map: "main",
    area: "Flanders Wallonia",
    port: true,
  },
  {
    name: "Brunei",
    type: "city",
    top: "82",
    left: "3.85",
    size: "small",
    kingdomCaptial: "Brunei",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "Budejovice",
    type: "city",
    top: "46.8",
    left: "54.75",
    size: "small",
    kingdomCaptial: "Praha",
    map: "main",
    area: "Bohemia",
    port: false,
  },
  {
    name: "Burgos",
    type: "city",
    top: "66.4",
    left: "25.5",
    size: "small",
    kingdomCaptial: "Madrid",
    map: "main",
    area: "Castile",
    port: false,
  },
  {
    name: "Burma",
    type: "city",
    top: "77.1",
    left: "0.3",
    size: "small",
    kingdomCaptial: "Burma",
    map: "distant",
    area: "Far East",
    port: false,
  },
  {
    name: "Buzau",
    type: "city",
    top: "59.25",
    left: "73.3",
    size: "small",
    kingdomCaptial: "Tirgoviste",
    map: "expansion",
    area: "Wallachia Bulgaria",
    port: false,
  },
  {
    name: "Caffa",
    type: "city",
    top: "58.7",
    left: "84.45",
    size: "small",
    kingdomCaptial: "Crimea",
    map: "expansion",
    area: "Crimea",
    port: true,
  },
  {
    name: "California",
    type: "territory",
    top: "8.2",
    left: "0.35",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Canada",
    type: "territory",
    top: "3.1",
    left: "5.14",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Canarias",
    type: "city",
    top: "94.9",
    left: "13.26",
    size: "small",
    kingdomCaptial: "Madrid",
    map: "main",
    area: "Macaronesia",
    port: true,
  },
  {
    name: "Canton",
    type: "city",
    top: "75.1",
    left: "2.4",
    size: "large",
    kingdomCaptial: "Beijing",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "Cape of Good Hope",
    type: "territory",
    top: "48.9%",
    left: "5.9",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "Africa",
    port: true,
  },
  {
    name: "Caux",
    type: "city",
    top: "43.8",
    left: "32.65",
    size: "small",
    kingdomCaptial: "London",
    map: "main",
    area: "Brittany Normandy",
    port: true,
  },
  {
    name: "Central Africa",
    type: "city",
    top: "40",
    left: "7",
    size: "large",
    kingdomCaptial: "Central Africa",
    map: "distant",
    area: "Africa",
    port: false,
  },
  {
    name: "Central America",
    type: "city",
    top: "11.4",
    left: "3.3",
    size: "large",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Cernigovas",
    type: "city",
    top: "40.7",
    left: "80.6",
    size: "small",
    kingdomCaptial: "Vilnius",
    map: "expansion",
    area: "Eastern Ukraine",
    port: false,
  },
  {
    name: "Ceuta",
    type: "city",
    top: "85.6",
    left: "23.9",
    size: "small",
    kingdomCaptial: "Lisboa",
    map: "main",
    area: "Northern Morocco",
    port: true,
  },
  {
    name: "Chagati",
    type: "city",
    top: "9",
    left: "87.5",
    size: "large",
    kingdomCaptial: "Chagati",
    map: "expansion",
    area: "Northen Central Asia",
    port: false,
    only: 1444,
  },
  {
    name: "Champagne",
    type: "city",
    top: "45.9",
    left: "38.2",
    size: "large",
    kingdomCaptial: "Paris",
    map: "main",
    area: "Seine",
    port: false,
  },
  {
    name: "Charcas",
    type: "city",
    top: "20.5",
    left: "6.8",
    size: "small",
    kingdomCaptial: "Cuzco",
    map: "distant",
    area: "America",
    port: false,
  },
  {
    name: "Chengdu",
    type: "city",
    top: "73.6",
    left: "0.65",
    size: "large",
    kingdomCaptial: "Beijing",
    map: "distant",
    area: "Far East",
    port: false,
  },
  {
    name: "Chile",
    type: "city",
    top: "24.2",
    left: "5.8",
    size: "small",
    kingdomCaptial: "Cuzco",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Circassia",
    type: "city",
    top: "61.8",
    left: "89",
    size: "small",
    kingdomCaptial: "Circassia",
    map: "expansion",
    area: "Circassia",
    port: false,
  },
  {
    name: "Constantinople",
    type: "city",
    top: "68.8",
    left: "74.7",
    size: "large",
    kingdomCaptial: "Constantinople",
    map: "expansion",
    area: "Macedonia Thrace",
    port: true,
  },
  {
    name: "Cordoba",
    type: "city",
    top: "78.5",
    left: "24.15",
    size: "small",
    kingdomCaptial: "Madrid",
    map: "main",
    area: "Andalucia",
    port: false,
  },
  {
    name: "Coromandel",
    type: "city",
    top: "65.7",
    left: "8.3",
    size: "small",
    kingdomCaptial: "Deccan",
    map: "distant",
    area: "India Arabia",
    port: true,
  },
  {
    name: "Corsica",
    type: "city",
    top: "68.3",
    left: "46.9",
    size: "small",
    kingdomCaptial: "Genova",
    map: "main",
    area: "Corsica Sardinia",
    port: true,
  },
  {
    name: "Creta",
    type: "city",
    top: "86.2",
    left: "71.05",
    size: "small",
    kingdomCaptial: "Venezia",
    map: "expansion",
    area: "Aegean Archipelago",
    port: true,
  },
  {
    name: "Crimea",
    type: "city",
    top: "57.6",
    left: "82.46",
    size: "small",
    kingdomCaptial: "Crimea",
    map: "expansion",
    area: "Crimea",
    port: true,
  },
  {
    name: "Cuzco",
    type: "city",
    top: "18.2",
    left: "5.15",
    size: "large",
    kingdomCaptial: "Cuzco",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Cyprus",
    type: "city",
    top: "85.2",
    left: "81.1",
    size: "small",
    kingdomCaptial: "Cyprus",
    map: "expansion",
    area: "Cyprus",
    port: true,
  },
  {
    name: "Danzig",
    type: "city",
    top: "29.8",
    left: "60.8",
    size: "small",
    kingdomCaptial: "Marienburg",
    map: "main",
    area: "Prussia",
    port: true,
  },
  {
    name: "Deccan",
    type: "city",
    top: "62",
    left: "7.85",
    size: "large",
    kingdomCaptial: "Deccan",
    map: "distant",
    area: "India Arabia",
    port: false,
  },
  {
    name: "Delhi",
    type: "city",
    top: "56.9",
    left: "7.25",
    size: "large",
    kingdomCaptial: "Delhi",
    map: "distant",
    area: "India Arabia",
    port: false,
  },
  {
    name: "Dimashq",
    type: "city",
    top: "87",
    left: "84.75",
    size: "small",
    kingdomCaptial: "Qahirah",
    map: "expansion",
    area: "Syria",
    port: false,
  },
  {
    name: "Doab",
    type: "city",
    top: "58.6",
    left: "8.6",
    size: "large",
    kingdomCaptial: "Delhi",
    map: "distant",
    area: "India Arabia",
    port: false,
  },
  {
    name: "Don",
    type: "city",
    top: "48.6",
    left: "90.8",
    size: "small",
    kingdomCaptial: "Saratov",
    map: "expansion",
    area: "Saratov",
    port: false,
    only: 1444,
  },
  {
    name: "Dresden",
    type: "city",
    top: "40.2",
    left: "53.55",
    size: "small",
    kingdomCaptial: "Dresden",
    map: "main",
    area: "Saxony",
    port: false,
  },
  {
    name: "Dumyat",
    type: "city",
    top: "92",
    left: "75.1",
    size: "small",
    kingdomCaptial: "Qahirah",
    map: "expansion",
    area: "Egypt",
    port: true,
  },
  {
    name: "Eatern Australia",
    type: "territory",
    top: "91.3",
    left: "10.6%",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "East Siberia",
    type: "territory",
    top: "4.45",
    left: "91.75",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "Northern Central Asia",
    port: false,
  },
  {
    name: "Edirne",
    type: "city",
    top: "69",
    left: "72",
    size: "large",
    kingdomCaptial: "Edirne",
    map: "expansion",
    area: "Macedonia Thrace",
    port: false,
  },
  {
    name: "Edisanas",
    type: "city",
    top: "55",
    left: "78.9",
    size: "small",
    kingdomCaptial: "Vilnius",
    map: "expansion",
    area: "Moldavia",
    port: false,
  },
  {
    name: "Erzurum",
    type: "city",
    top: "71.9",
    left: "90.35",
    size: "small",
    kingdomCaptial: "Mush",
    map: "expansion",
    area: "Rum",
    port: false,
  },
  {
    name: "Essex",
    type: "city",
    top: "35.4",
    left: "33.55",
    size: "small",
    kingdomCaptial: "London",
    map: "main",
    area: "East Anglia",
    port: true,
  },
  {
    name: "Ethiopia",
    type: "city",
    top: "36.2",
    left: "8.3",
    size: "large",
    kingdomCaptial: "Ethiopia",
    map: "distant",
    area: "Africa",
    port: false,
  },
  {
    name: "Fars",
    type: "city",
    top: "59.2",
    left: "2.85",
    size: "small",
    kingdomCaptial: "Fars",
    map: "distant",
    area: "India Arabia",
    port: false,
  },
  {
    name: "Fayyum (1444)",
    type: "city",
    top: "75.55",
    left: "95.2",
    size: "small",
    kingdomCaptial: "Qahirah",
    map: "expansion",
    area: "Egypt",
    port: false,
  },
  {
    name: "Ferrara",
    type: "city",
    top: "62.5",
    left: "51.44",
    size: "small",
    kingdomCaptial: "Ferrara",
    map: "main",
    area: "Central Italy",
    port: true,
  },
  {
    name: "Fez",
    type: "city",
    top: "25.35",
    left: "25.3",
    size: "small",
    kingdomCaptial: "Fez",
    map: "main",
    area: "Northern Morocco",
    port: false,
  },
  {
    name: "Firenze",
    type: "city",
    top: "64.6",
    left: "49.7",
    size: "large",
    kingdomCaptial: "Firenze",
    map: "main",
    area: "Central Italy",
    port: false,
  },
  {
    name: "Florida",
    type: "territory",
    top: "8.85",
    left: "4.2",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Franche Comte",
    type: "city",
    top: "51.7",
    left: "41.55",
    size: "small",
    kingdomCaptial: "Bourgogne",
    map: "main",
    area: "Burgundy",
    port: false,
  },
  {
    name: "Frankfurt",
    type: "city",
    top: "41.75",
    left: "46",
    size: "small",
    kingdomCaptial: "Frankfurt",
    map: "main",
    area: "Westphalia",
    port: false,
  },
  {
    name: "Friesland",
    type: "city",
    top: "31.6",
    left: "41.9",
    size: "small",
    kingdomCaptial: "Friesland",
    map: "main",
    area: "Netherlands",
    port: true,
  },
  {
    name: "Furdan",
    type: "city",
    top: "9.7",
    left: "94.9",
    size: "small",
    kingdomCaptial: "Manchu",
    map: "distant",
    area: "Northern Central Asia",
    port: false,
  },
  {
    name: "Galich",
    type: "city",
    top: "22.6",
    left: "92",
    size: "small",
    kingdomCaptial: "Moskva",
    map: "main",
    area: "Perm",
    port: false,
  },
  {
    name: "Galicia",
    type: "city",
    top: "61.2",
    left: "19.45",
    size: "small",
    kingdomCaptial: "Madrid",
    map: "main",
    area: "Leon",
    port: true,
  },
  {
    name: "Gazzah",
    type: "city",
    top: "92.5",
    left: "81.2",
    size: "small",
    kingdomCaptial: "Qahirah",
    map: "main",
    area: "Palestine",
    port: true,
  },
  {
    name: "Gelre",
    type: "city",
    top: "34.9",
    left: "42.2",
    size: "small",
    kingdomCaptial: "Gelre",
    map: "main",
    area: "Netherlands",
    port: false,
  },
  {
    name: "Genova",
    type: "city",
    top: "62",
    left: "45.75",
    size: "large",
    kingdomCaptial: "Genova",
    map: "main",
    area: "Lombardy",
    port: true,
  },
  {
    name: "Geneve",
    type: "city",
    top: "54.3",
    left: "42.85",
    size: "small",
    kingdomCaptial: "Savoie",
    map: "main",
    area: "Switzerland",
    port: false,
  },
  {
    name: "Gent",
    type: "city",
    top: "39.2",
    left: "38.2",
    size: "small",
    kingdomCaptial: "Brugge",
    map: "main",
    area: "Flanders Wallonia",
    port: true,
  },
  {
    name: "Gharb",
    type: "city",
    top: "90",
    left: "20.05",
    size: "small",
    kingdomCaptial: "Fez",
    map: "main",
    area: "Northern Morocco",
    port: true,
  },
  {
    name: "Gibraltar",
    type: "city",
    top: "83",
    left: "22.7",
    size: "small",
    kingdomCaptial: "Granada",
    map: "main",
    area: "Andalucia",
    port: true,
  },
  {
    name: "Goa",
    type: "city",
    top: "63.6",
    left: "7.1",
    size: "small",
    kingdomCaptial: "Goa",
    map: "distant",
    area: "India Arabia",
    port: true,
  },
  {
    name: "Gold Coast",
    type: "territory",
    top: "37.9",
    left: "1.9",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "Africa",
    port: true,
  },
  {
    name: "Goldingen",
    type: "city",
    top: "22.1",
    left: "65.3",
    size: "small",
    kingdomCaptial: "Livland",
    map: "main",
    area: "Estonia Livonia",
    port: true,
  },
  {
    name: "Gotland",
    type: "city",
    top: "20.2",
    left: "60.7",
    size: "small",
    kingdomCaptial: "Koberhaven",
    map: "main",
    area: "Gotaland Skane",
    port: true,
  },
  {
    name: "Granada",
    type: "city",
    top: "80.4",
    left: "25.8",
    size: "small",
    kingdomCaptial: "Granada",
    map: "main",
    area: "Andalucia",
    port: false,
  },
  {
    name: "Great Lakes",
    type: "territory",
    top: "5",
    left: "3.5",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: false,
  },
  {
    name: "Great Plains",
    type: "territory",
    top: "5.2",
    left: "1.65",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: false,
  },
  {
    name: "Gujarat",
    type: "city",
    top: "60",
    left: "6",
    size: "large",
    kingdomCaptial: "Gujarat",
    map: "distant",
    area: "India Arabia",
    port: true,
  },
  {
    name: "Guria",
    type: "city",
    top: "67.2",
    left: "91.2",
    size: "small",
    kingdomCaptial: "Imereti",
    map: "main",
    area: "Circassia",
    port: true,
  },
  {
    name: "Guyana",
    type: "territory",
    top: "14.2",
    left: "7.5",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Halab",
    type: "city",
    top: "80.1",
    left: "85.2",
    size: "large",
    kingdomCaptial: "Qahirah",
    map: "main",
    area: "Syria",
    port: false,
  },
  {
    name: "Halsingland",
    type: "city",
    top: "6",
    left: "59.45",
    size: "small",
    kingdomCaptial: "Stockholm",
    map: "main",
    area: "Norrland",
    port: false,
  },
  {
    name: "Hamburg",
    type: "city",
    top: "32",
    left: "47.85",
    size: "small",
    kingdomCaptial: "Hamburg",
    map: "main",
    area: "Lower Saxony",
    port: true,
  },
  {
    name: "Hangzhou",
    type: "territory",
    top: "73.5",
    left: "4.1",
    size: "large",
    kingdomCaptial: "Beijing",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "Hannover",
    type: "city",
    top: "35.9",
    left: "47.45",
    size: "small",
    kingdomCaptial: "Braunschweig",
    map: "main",
    area: "Lower Saxony",
    port: false,
  },
  {
    name: "Herat",
    type: "city",
    top: "56.5",
    left: "3.5",
    size: "large",
    kingdomCaptial: "Herat",
    map: "distant",
    area: "India Arabia",
    port: false,
  },
  {
    name: "Hejaz",
    type: "city",
    top: "61.5",
    left: "0.2",
    size: "small",
    kingdomCaptial: "Hejaz",
    map: "distant",
    area: "India Arabia",
    port: true,
  },
  {
    name: "Holstein",
    type: "city",
    top: "28.8",
    left: "48.14",
    size: "small",
    kingdomCaptial: "Holstein",
    map: "main",
    area: "Jutland",
    port: true,
  },
  {
    name: "Honshu",
    type: "city",
    top: "70.6",
    left: "8.2",
    size: "large",
    kingdomCaptial: "Honshu",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "Hormuz",
    type: "city",
    top: "61.6",
    left: "3.35",
    size: "small",
    kingdomCaptial: "Hormuz",
    map: "distant",
    area: "India Arabia",
    port: true,
  },
  {
    name: "Hudavendigar",
    type: "city",
    top: "72.2",
    left: "74.1",
    size: "large",
    kingdomCaptial: "Edirne",
    map: "main",
    area: "Northern Anatolia",
    port: true,
  },
  {
    name: "Hudson Bay",
    type: "territory",
    top: "1.85",
    left: "3.25",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Hum",
    type: "city",
    top: "63.2",
    left: "59",
    size: "small",
    kingdomCaptial: "Bosnia",
    map: "main",
    area: "Croatia Bosnia",
    port: false,
    only: 1444,
  },
  {
    name: "Hunyad",
    type: "city",
    top: "57.2",
    left: "67.1",
    size: "small",
    kingdomCaptial: "Pest",
    map: "main",
    area: "Transylvania",
    port: false,
  },
  {
    name: "Imereti",
    type: "city",
    top: "65",
    left: "92.25",
    size: "small",
    kingdomCaptial: "Imereti",
    map: "main",
    area: "Circassia",
    port: false,
  },
  {
    name: "Isfahan",
    type: "city",
    top: "55.5",
    left: "1.7",
    size: "large",
    kingdomCaptial: "Isfahan",
    map: "distant",
    area: "India Arabia",
    port: false,
  },
  {
    name: "Iskandariyya",
    type: "city",
    top: "92",
    left: "75.1",
    size: "small",
    kingdomCaptial: "Qahirah",
    map: "main",
    area: "Egypt",
    port: true,
  },
  {
    name: "Izmir",
    type: "city",
    top: "78.1",
    left: "73.3",
    size: "small",
    kingdomCaptial: "Edirne",
    map: "main",
    area: "Aydin",
    port: true,
  },
  {
    name: "Jaffa",
    type: "city",
    top: "90",
    left: "83.1",
    size: "small",
    kingdomCaptial: "Qahirah",
    map: "main",
    area: "Palestine",
    port: true,
  },
  {
    name: "Java",
    type: "city",
    top: "85.6",
    left: "3.4",
    size: "small",
    kingdomCaptial: "Java",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "Kabylia",
    type: "city",
    top: "84.7",
    left: "40.7",
    size: "small",
    kingdomCaptial: "Tunis",
    map: "main",
    area: "Algiers",
    port: true,
  },
  {
    name: "Kalisz",
    type: "city",
    top: "37.8",
    left: "60.4",
    size: "small",
    kingdomCaptial: "Krakow",
    map: "main",
    area: "Wielkopolska",
    port: false,
  },
  {
    name: "Karaman",
    type: "city",
    top: "81.4",
    left: "80.6",
    size: "small",
    kingdomCaptial: "Karaman",
    map: "main",
    area: "Karaman",
    port: true,
  },
  {
    name: "Kargopol",
    type: "city",
    top: "4.15",
    left: "80.5",
    size: "small",
    kingdomCaptial: "Novgorod",
    map: "main",
    area: "Pomorye",
    port: false,
    only: 1444,
  },
  {
    name: "Karnten",
    type: "city",
    top: "53.6",
    left: "53.1",
    size: "small",
    kingdomCaptial: "Wien",
    map: "main",
    area: "Tirol",
    port: false,
  },
  {
    name: "Kasimov",
    type: "city",
    top: "32.8",
    left: "90.3",
    size: "small",
    kingdomCaptial: "Moskva",
    map: "main",
    area: "Central Russia",
    port: false,
    only: 1444,
  },
  {
    name: "Kastamonu",
    type: "city",
    top: "68.3",
    left: "81.7",
    size: "small",
    kingdomCaptial: "Kastamonu",
    map: "main",
    area: "Northern Anatolia",
    port: true,
  },
  {
    name: "Katsina",
    type: "city",
    top: "36.4",
    left: "4.7",
    size: "small",
    kingdomCaptial: "Katsina",
    map: "distant",
    area: "Africa",
    port: false,
  },
  {
    name: "Kaunas",
    type: "city",
    top: "30.5",
    left: "68.45",
    size: "small",
    kingdomCaptial: "Vilnius",
    map: "main",
    area: "Lithuania",
    port: false,
    only: 1444,
  },
  {
    name: "Kazakhstan",
    type: "territory",
    top: "8",
    left: "85.4",
    size: "large",
    kingdomCaptial: "Tyumen",
    map: "distant",
    area: "Northern Central Asia",
    port: false,
  },
  {
    name: "Kazan",
    type: "city",
    top: "29.1",
    left: "96.1",
    size: "small",
    kingdomCaptial: "Kazan",
    map: "main",
    area: "Kazan",
    port: false,
  },
  {
    name: "Khiva",
    type: "city",
    top: "54.2",
    left: "3.35",
    size: "small",
    kingdomCaptial: "Samarkand",
    map: "distant",
    area: "India Arabia",
    port: false,
  },
  {
    name: "Kijevas",
    type: "city",
    top: "44.5",
    left: "77.2",
    size: "small",
    kingdomCaptial: "Vilnius",
    map: "main",
    area: "Western Ukraine",
    port: false,
  },
  {
    name: "Kilwa",
    type: "city",
    top: "42.8",
    left: "8.9",
    size: "small",
    kingdomCaptial: "Kilwa",
    map: "distant",
    area: "Africa",
    port: true,
  },
  {
    name: "Kirkuk",
    type: "city",
    top: "82.15",
    left: "94.85",
    size: "small",
    kingdomCaptial: "Tabriz",
    map: "main",
    area: "Iraq",
    port: false,
  },
  {
    name: "Kleve",
    type: "city",
    top: "37.7",
    left: "43.1",
    size: "small",
    kingdomCaptial: "Kleve",
    map: "main",
    area: "Westphalia",
    port: false,
  },
  {
    name: "Kobenhavn",
    type: "city",
    top: "23.8",
    left: "50.7",
    size: "large",
    kingdomCaptial: "Kobenhavn",
    map: "main",
    area: "Sjaelland Fyn",
    port: true,
  },
  {
    name: "Koln",
    type: "city",
    top: "40.5",
    left: "43",
    size: "small",
    kingdomCaptial: "Koln",
    map: "main",
    area: "Westphalia",
    port: false,
  },
  {
    name: "Kongo",
    type: "territory",
    top: "40.5",
    left: "4.5",
    size: "large",
    kingdomCaptial: "Kongo",
    map: "distant",
    area: "Africa",
    port: false,
  },
  {
    name: "Konisberg",
    type: "city",
    top: "28.6",
    left: "64.1",
    size: "small",
    kingdomCaptial: "Marienburg",
    map: "main",
    area: "Prussia",
    port: true,
  },
  {
    name: "Konya",
    type: "city",
    top: "77.5",
    left: "79.9",
    size: "small",
    kingdomCaptial: "Karaman",
    map: "main",
    area: "Karaman",
    port: false,
    only: 1444,
  },
  {
    name: "Korea",
    type: "city",
    top: "71.5",
    left: "6.2",
    size: "small",
    kingdomCaptial: "Korea",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "Kosovo",
    type: "city",
    top: "68.2",
    left: "64.1",
    size: "small",
    kingdomCaptial: "Smederevo",
    map: "main",
    area: "Serbia Albania",
    port: false,
  },
  {
    name: "Krain",
    type: "city",
    top: "58.2",
    left: "53.95",
    size: "small",
    kingdomCaptial: "Wien",
    map: "main",
    area: "Venetia",
    port: false,
  },
  {
    name: "Krakow",
    type: "city",
    top: "43.7",
    left: "62.7",
    size: "large",
    kingdomCaptial: "Krakow",
    map: "main",
    area: "Mazovia Malopolska",
    port: false,
  },
  {
    name: "Kulm",
    type: "city",
    top: "34",
    left: "60.9",
    size: "small",
    kingdomCaptial: "Marienburg",
    map: "main",
    area: "Prussia",
    port: false,
  },
  {
    name: "Kutahya",
    type: "city",
    top: "76",
    left: "76.7",
    size: "small",
    kingdomCaptial: "Edirne",
    map: "main",
    area: "Aydin",
    port: false,
  },
  {
    name: "Kyushu",
    type: "city",
    top: "73.1",
    left: "7.35",
    size: "small",
    kingdomCaptial: "Honshu",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "Kyzy-Yar",
    type: "city",
    top: "53.4",
    left: "85.3",
    size: "small",
    kingdomCaptial: "Crimea",
    map: "main",
    area: "Crimea",
    port: false,
  },
  {
    name: "Ladoga",
    type: "city",
    top: "15.6",
    left: "78.5",
    size: "small",
    kingdomCaptial: "Novgorod",
    map: "main",
    area: "Karelia",
    port: false,
  },
  {
    name: "Laighin",
    type: "city",
    top: "32.5",
    left: "20.6",
    size: "small",
    kingdomCaptial: "Laighin",
    map: "main",
    area: "Ireland",
    port: true,
  },
  {
    name: "Lancashire",
    type: "city",
    top: "28.8",
    left: "27.6",
    size: "small",
    kingdomCaptial: "London",
    map: "main",
    area: "Northumbria",
    port: true,
  },
  {
    name: "Landshut",
    type: "city",
    top: "48.3",
    left: "52.5",
    size: "small",
    kingdomCaptial: "Munchen",
    map: "main",
    area: "Bavaria Swabia",
    port: false,
  },
  {
    name: "La Plata",
    type: "territory",
    top: "23.9",
    left: "7.5",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Leipzig",
    type: "city",
    top: "40.2",
    left: "49.9",
    size: "small",
    kingdomCaptial: "Dresden",
    map: "main",
    area: "Saxony",
    port: false,
  },
  {
    name: "Liege",
    type: "city",
    top: "40.8",
    left: "41.5",
    size: "small",
    kingdomCaptial: "Liege",
    map: "main",
    area: "Flanders Wallonia",
    port: false,
  },
  {
    name: "Lienz",
    type: "city",
    top: "53.8",
    left: "51.4",
    size: "small",
    kingdomCaptial: "Wien",
    map: "main",
    area: "Tirol",
    port: false,
  },
  {
    name: "Limousin",
    type: "city",
    top: "58.5",
    left: "34.75",
    size: "small",
    kingdomCaptial: "Paris",
    map: "main",
    area: "Loire",
    port: false,
  },
  {
    name: "Lisboa",
    type: "city",
    top: "74.3",
    left: "17.1",
    size: "large",
    kingdomCaptial: "Lisboa",
    map: "main",
    area: "Portugal",
    port: true,
  },
  {
    name: "Livland",
    type: "city",
    top: "20.6",
    left: "69.6",
    size: "small",
    kingdomCaptial: "Livland",
    map: "main",
    area: "Estonia Livonia",
    port: true,
  },
  {
    name: "Lorraine",
    type: "city",
    top: "47.3",
    left: "41.8",
    size: "large",
    kingdomCaptial: "Lorraine",
    map: "main",
    area: "Rhineland",
    port: false,
  },
  {
    name: "London",
    type: "city",
    top: "36.2",
    left: "31.2",
    size: "large",
    kingdomCaptial: "London",
    map: "main",
    area: "East Anglia",
    port: true,
  },
  {
    name: "Lothian",
    type: "city",
    top: "21.9",
    left: "26.7",
    size: "small",
    kingdomCaptial: "Lothian",
    map: "main",
    area: "Scotland",
    port: true,
  },
  {
    name: "Lubeck",
    type: "city",
    top: "30.4",
    left: "50.1",
    size: "small",
    kingdomCaptial: "Lubeck",
    map: "main",
    area: "Pomerania",
    port: true,
  },
  {
    name: "Lublin",
    type: "city",
    top: "41.5",
    left: "66.4",
    size: "small",
    kingdomCaptial: "Krakow",
    map: "main",
    area: "Mazovia Malopolska",
    port: false,
  },
  {
    name: "Luxembourg",
    type: "city",
    top: "44.2",
    left: "41.5",
    size: "small",
    kingdomCaptial: "Bourgogne",
    map: "main",
    area: "Flanders Wallonia",
    port: false,
  },
  {
    name: "Lwow",
    type: "city",
    top: "47.6",
    left: "69.9",
    size: "small",
    kingdomCaptial: "Krakow",
    map: "main",
    area: "Red Ruthenia",
    port: false,
  },
  {
    name: "Lyon",
    type: "city",
    top: "57.2",
    left: "39.3",
    size: "large",
    kingdomCaptial: "Paris",
    map: "main",
    area: "Burgundy",
    port: false,
  },
  {
    name: "Madagascar",
    type: "city",
    top: "44.84",
    left: "10.22",
    size: "small",
    kingdomCaptial: "Madagascar",
    map: "distant",
    area: "Africa",
    port: true,
  },
  {
    name: "Madeira",
    type: "city",
    top: "86.71",
    left: "13.2",
    size: "small",
    kingdomCaptial: "Lisboa",
    map: "main",
    area: "Macaronesia",
    port: false,
  },
  {
    name: "Madrid",
    type: "city",
    top: "70.92",
    left: "25.52",
    size: "large",
    kingdomCaptial: "Madrid",
    map: "main",
    area: "Castile",
    port: false,
  },
  {
    name: "Magdeburg",
    type: "city",
    top: "36.41",
    left: "50.46",
    size: "small",
    kingdomCaptial: "Magdeburg",
    map: "main",
    area: "Lower Saxony",
    port: false,
  },
  {
    name: "Maine",
    type: "city",
    top: "49.56",
    left: "31.8",
    size: "small",
    kingdomCaptial: "London",
    map: "main",
    area: "Brittany Normandy",
    port: false,
  },
  {
    name: "Mainz",
    type: "city",
    top: "44.53",
    left: "46.15",
    size: "small",
    kingdomCaptial: "Mainz",
    map: "main",
    area: "Rhineland",
    port: false,
  },
  {
    name: "Majar",
    type: "city",
    top: "57.11",
    left: "92",
    size: "small",
    kingdomCaptial: "Saratov",
    map: "expansion",
    area: "Astrakhan",
    port: false,
  },
  {
    name: "Malacca",
    type: "city",
    top: "82.23",
    left: "2.02",
    size: "small",
    kingdomCaptial: "Malacca",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "Mali",
    type: "city",
    top: "35.81",
    left: "0.11",
    size: "large",
    kingdomCaptial: "Mali",
    map: "distant",
    area: "Africa",
    port: true,
  },
  {
    name: "Malta",
    type: "city",
    top: "87.39",
    left: "54.38",
    size: "small",
    kingdomCaptial: "Valencia",
    map: "main",
    area: "Sicily",
    port: true,
  },
  {
    name: "Manchu",
    type: "city",
    top: "9.46",
    left: "93.45",
    size: "small",
    kingdomCaptial: "Manchu",
    map: "expansion",
    area: "Northern Central Asia",
    port: false,
  },
  {
    name: "Mantova",
    type: "city",
    top: "61.39",
    left: "48.96",
    size: "small",
    kingdomCaptial: "Mantova",
    map: "main",
    area: "Lombardy",
    port: false,
  },
  {
    name: "Marienburg",
    type: "city",
    top: "30.82",
    left: "62.69",
    size: "small",
    kingdomCaptial: "Marienburg",
    map: "main",
    area: "Prussia",
    port: false,
  },
  {
    name: "Mentese",
    type: "city",
    top: "81.1",
    left: "75",
    size: "small",
    kingdomCaptial: "Edirne",
    map: "main",
    area: "Aydin",
    port: true,
  },
  {
    name: "Marrakech",
    type: "city",
    top: 93.1,
    left: 19.6,
    size: "small",
    kingdomCaptial: "Fez",
    map: "main",
    area: "Northern Morocco",
    port: false,
  },
  {
    name: "Mecklenburg",
    type: "city",
    top: 30,
    left: 51.85,
    size: "small",
    kingdomCaptial: "Mecklenburg",
    map: "main",
    area: "Pomerania",
    port: true,
  },
  {
    name: "Mesina",
    type: "city",
    top: 82.25,
    left: 54.96,
    size: "small",
    kingdomCaptial: "Valencia",
    map: "main",
    area: "Sicily",
    port: true,
  },
  {
    name: "Mexico",
    type: "city",
    top: "10.67",
    left: "1.41",
    size: "large",
    kingdomCaptial: "Mexico",
    map: "distant",
    area: "North America",
    port: true,
  },
  {
    name: "Mhumhain",
    type: "city",
    top: "33.77",
    left: "18.29",
    size: "small",
    kingdomCaptial: "Mhumhain",
    map: "main",
    area: "Ireland",
    port: true,
  },
  {
    name: "Milano",
    type: "city",
    top: "56.93",
    left: "45.68",
    size: "large",
    kingdomCaptial: "Milano",
    map: "main",
    area: "Lombardy",
    port: false,
  },
  {
    name: "Minas Gerais",
    type: "territory",
    top: "17.00",
    left: "7.22",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: false,
  },
  {
    name: "Minskas",
    type: "city",
    top: "33.73",
    left: "74.2",
    size: "small",
    kingdomCaptial: "Vilnius",
    map: "main",
    area: "White Ruthenia",
    port: false,
  },
  {
    name: "Mississippi",
    type: "territory",
    top: "8.09",
    left: "2.71",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Mitidja",
    type: "city",
    top: "84.2",
    left: "37.76",
    size: "small",
    kingdomCaptial: "Tunis",
    map: "main",
    area: "Algiers",
    port: true,
  },
  {
    name: "Moluccas",
    type: "territory",
    top: "83.53",
    left: "5.82",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "Mongolia",
    type: "territory",
    top: "8.56",
    left: "91.34",
    size: "large",
    kingdomCaptial: "Mongolia",
    map: "expansion",
    area: "Central Asia",
    port: false,
  },
  {
    name: "Montpellier",
    type: "city",
    top: "64.11",
    left: "38.27",
    size: "small",
    kingdomCaptial: "Paris",
    map: "main",
    area: "Languedoc",
    port: true,
  },
  {
    name: "Morea",
    type: "city",
    top: "83.37",
    left: "67.6",
    size: "small",
    kingdomCaptial: "Constantinople",
    map: "expansion",
    area: "Greece",
    port: false,
  },
  {
    name: "Moskva",
    type: "city",
    top: "28.4",
    left: "85.01",
    size: "small",
    kingdomCaptial: "Moskva",
    map: "expansion",
    area: "Moscow Ryazan",
    port: false,
  },
  {
    name: "Mosul",
    type: "city",
    top: "79.3",
    left: "93.12",
    size: "small",
    kingdomCaptial: "Tabriz",
    map: "expansion",
    area: "Kurdistan",
    port: false,
  },
  {
    name: "Munchen",
    type: "city",
    top: "49.76",
    left: "51.04",
    size: "small",
    kingdomCaptial: "Munchen",
    map: "main",
    area: "Bavaria Swabia",
    port: false,
  },
  {
    name: "Munster",
    type: "city",
    top: "36.77",
    left: "44.87",
    size: "small",
    kingdomCaptial: "Munster",
    map: "main",
    area: "Westphalia",
    port: false,
  },
  {
    name: "Murcia",
    type: "city",
    top: "79.75",
    left: "29.51",
    size: "small",
    kingdomCaptial: "Madrid",
    map: "main",
    area: "Castile",
    port: true,
  },
  {
    name: "Murom",
    type: "city",
    top: "29.93",
    left: "92.02",
    size: "small",
    kingdomCaptial: "Moskva",
    map: "expansion",
    area: "Central Russia",
    port: false,
  },
  {
    name: "Mush",
    type: "city",
    top: "75.07",
    left: "90.42",
    size: "small",
    kingdomCaptial: "Mush",
    map: "expansion",
    area: "Kurdistan",
    port: false,
  },
  {
    name: "Mutapa",
    type: "city",
    top: "44.87",
    left: "7.62",
    size: "small",
    kingdomCaptial: "Mutapa",
    map: "distant",
    area: "Africa",
    port: false,
  },
  {
    name: "Najd",
    type: "city",
    top: "60.36",
    left: "1.22",
    size: "small",
    kingdomCaptial: "Najd",
    map: "distant",
    area: "India Arabia",
    port: false,
  },
  {
    name: "Namur",
    type: "city",
    top: "43.07",
    left: "39.07",
    size: "small",
    kingdomCaptial: "Bourgogne",
    map: "main",
    area: "Flanders Wallonia",
    port: false,
  },
  {
    name: "Nantes",
    type: "city",
    top: "50.76",
    left: "28.95",
    size: "small",
    kingdomCaptial: "Nantes",
    map: "main",
    area: "Brittany Normandy",
    port: true,
  },
  {
    name: "Napoli",
    type: "city",
    top: "73.29",
    left: "54.53",
    size: "large",
    kingdomCaptial: "Napoli",
    map: "main",
    area: "Naples",
    port: true,
  },
  {
    name: "Natal",
    type: "territory",
    top: "47.94",
    left: "7.47",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "Africa",
    port: true,
  },
  {
    name: "Naugardukas",
    type: "city",
    top: "36",
    left: "71.5",
    size: "small",
    kingdomCaptial: "Vilnius",
    map: "main",
    area: "Red Ruthenia",
    port: false,
    only: 1444,
  },
  {
    name: "Navarra",
    type: "city",
    top: "64.16",
    left: "28.95",
    size: "small",
    kingdomCaptial: "Navarra",
    map: "main",
    area: "Aragon",
    port: true,
  },
  {
    name: "Naxos",
    type: "city",
    top: "80.47",
    left: "71.5",
    size: "small",
    kingdomCaptial: "Naxos",
    map: "main",
    area: "Aegean Archipelago",
    port: true,
  },
  
  {
    name: "Neva",
    type: "territory",
    top: "16.19",
    left: "76.25",
    size: "small",
    kingdomCaptial: "Novgorod",
    map: "expansion",
    area: "Karelia",
    port: true,
  },
  {
    name: "New England",
    type: "territory",
    top: "5.16",
    left: "6.31",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "New Granada",
    type: "territory",
    top: "13.62",
    left: "5.82",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Nizhny Novgorod",
    type: "city",
    top: "26.45",
    left: "92.92",
    size: "small",
    kingdomCaptial: "Moskva",
    map: "expansion",
    area: "Perm",
    port: false,
  },
  {
    name: "Nogai",
    type: "city",
    top: "8.46",
    left: "83.33",
    size: "large",
    kingdomCaptial: "Nogai",
    map: "expansion",
    area: "Northern Central Asia",
    port: false,
  },
  {
    name: "Normandie",
    type: "city",
    top: "45.53",
    left: "30.9",
    size: "small",
    kingdomCaptial: "London",
    map: "main",
    area: "Brittany Normandy",
    port: true,
  },
  {
    name: "Northumberland",
    type: "city",
    top: "24.19",
    left: "28.45",
    size: "small",
    kingdomCaptial: "London",
    map: "main",
    area: "Northumbria",
    port: true,
  },
  {
    name: "Novgorod",
    type: "city",
    top: "19.19",
    left: "78.65",
    size: "large",
    kingdomCaptial: "Novgorod",
    map: "expansion",
    area: "Novgorod",
    port: false,
  },
  {
    name: "Nurnberg",
    type: "city",
    top: "44.88",
    left: "49.88",
    size: "small",
    kingdomCaptial: "Nurnberg",
    map: "main",
    area: "Saxony",
    port: false,
  },
  {
    name: "Nyland",
    type: "city",
    top: "13.71",
    left: "70.8",
    size: "small",
    kingdomCaptial: "Stockholm",
    map: "main",
    area: "Finland",
    port: true,
  },
  {
    name: "Odoyev",
    type: "city",
    top: "35.1",
    left: "84.61",
    size: "small",
    kingdomCaptial: "Odoyev",
    map: "expansion",
    area: "Moscow Ryazan",
    port: false,
  },
  {
    name: "Oirat",
    type: "city",
    left: "88.93",
    top: "6.9",
    size: "large",
    kingdomCaptial: "Oirat",
    map: "expansion",
    area: "Northern Central Asia",
    port: false,
  },
  {
    name: "Okhotsk",
    type: "territory",
    left: "94.85",
    top: "4.8",
    size: "small",
    kingdomCaptial: "",
    map: "expansion",
    area: "Northern Central Asia",
    port: false,
  },
  {
    name: "Olomouc",
    type: "city",
    left: "58.59",
    top: "44.7",
    size: "small",
    kingdomCaptial: "Praha",
    map: "main",
    area: "Bohemia",
    port: false,
  },
  {
    name: "Olonets",
    type: "city",
    left: "80.7",
    top: "10.78",
    size: "small",
    kingdomCaptial: "Novgorod",
    map: "expansion",
    area: "Karelia",
    port: false,
  },
  {
    name: "Oran",
    type: "city",
    left: "34.05",
    top: "85.57",
    size: "small",
    kingdomCaptial: "Tlemcen",
    map: "main",
    area: "Algiers",
    port: true,
  },
  {
    name: "Orleans",
    type: "city",
    top: "50.56",
    left: "33.66",
    size: "large",
    kingdomCaptial: "Paris",
    map: "main",
    area: "Loire",
    port: false,
  },
  {
    name: "Osterbotten",
    type: "city",
    top: "2.53",
    left: "68.4",
    size: "small",
    kingdomCaptial: "Stockholm",
    map: "main",
    area: "Ostrobothnia",
    port: false,
  },
  {
    name: "Ostergotland",
    type: "city",
    top: "17.81",
    left: "57.69",
    size: "small",
    kingdomCaptial: "Stockholm",
    map: "main",
    area: "Gotaland Skane",
    port: true,
  },
  {
    name: "Osterreich",
    type: "city",
    top: "47.96",
    left: "56.68",
    size: "small",
    kingdomCaptial: "Wien",
    map: "main",
    area: "Austria",
    port: false,
  },
  {
    name: "Ostylland",
    type: "city",
    top: "22.34",
    left: "48.18",
    size: "small",
    kingdomCaptial: "Kobenhavn",
    map: "main",
    area: "Jutland",
    port: true,
  },
  {
    name: "Oxford",
    type: "city",
    top: "34.97",
    left: "29.85",
    size: "small",
    kingdomCaptial: "London",
    map: "main",
    area: "East Anglia",
    port: false,
  },
  {
    name: "Paris",
    type: "city",
    top: "46.1",
    left: "34.53",
    size: "large",
    kingdomCaptial: "Paris",
    map: "main",
    area: "Seine",
    port: false,
  },
  {
    name: "Pale",
    type: "city",
    top: "29.04",
    left: "21.14",
    size: "small",
    kingdomCaptial: "London",
    map: "main",
    area: "Ireland",
    port: true,
  },
  {
    name: "Palermo",
    type: "city",
    top: "82.27",
    left: "51.58",
    size: "small",
    kingdomCaptial: "Valencia",
    map: "main",
    area: "Sicily",
    port: true,
  },
  {
    name: "Papua",
    type: "territory",
    top: "85.03",
    left: "9.38",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "Parma",
    type: "city",
    top: "61.91",
    left: "47.82",
    size: "small",
    kingdomCaptial: "Milano",
    map: "main",
    area: "Lombardy",
    port: false,
  },
  {
    name: "Perm",
    type: "city",
    top: "14.64",
    left: "97.03",
    size: "small",
    kingdomCaptial: "Perm",
    map: "expansion",
    area: "Perm",
    port: false,
  },
  {
    name: "Pernambuco",
    type: "territory",
    top: "16.42",
    left: "10.32",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Perth",
    type: "city",
    top: "19.41",
    left: "25.45",
    size: "small",
    kingdomCaptial: "Lothian",
    map: "main",
    area: "Scotland",
    port: false,
  },
  {
    name: "Pest",
    type: "city",
    top: "52.43",
    left: "61.09",
    size: "small",
    kingdomCaptial: "Pest",
    map: "main",
    area: "Hungarian Plain",
    port: false,
  },
  {
    name: "Pfalz",
    type: "city",
    top: "46.05",
    left: "44.23",
    size: "small",
    kingdomCaptial: "Pfalz",
    map: "main",
    area: "Rhineland",
    port: false,
  },
  {
    name: "Philippines",
    type: "territory",
    top: "78.7",
    left: "5.52",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "Picardie",
    type: "city",
    top: "41.83",
    left: "34.73",
    size: "small",
    kingdomCaptial: "Bourgogne",
    map: "main",
    area: "Seine",
    port: true,
  },
  {
    name: "Piemonte",
    type: "city",
    top: "60.59",
    left: "43.88",
    size: "small",
    kingdomCaptial: "Savoie",
    map: "main",
    area: "Lombardy",
    port: false,
  },
  {
    name: "Pisa",
    type: "city",
    top: "66.59",
    left: "48.98",
    size: "small",
    kingdomCaptial: "Firenze",
    map: "main",
    area: "Central Italy",
    port: true,
  },
  {
    name: "Podole",
    type: "city",
    top: "48.29",
    left: "73.8",
    size: "small",
    kingdomCaptial: "Krakow",
    map: "expansion",
    area: "Western Ukraine",
    port: false,
  },
  {
    name: "Poitou",
    type: "city",
    top: "55.33",
    left: "32.62",
    size: "small",
    kingdomCaptial: "Paris",
    map: "main",
    area: "Aquitaine",
    port: false,
  },
  {
    name: "Polockas",
    type: "city",
    top: "28.2",
    left: "75.5",
    size: "small",
    kingdomCaptial: "Vilnius",
    map: "main",
    area: "White Ruthenia",
    port: false,
  },
  {
    name: "Poltava",
    type: "city",
    top: "46.49",
    left: "82.61",
    size: "small",
    kingdomCaptial: "Vilnius",
    map: "expansion",
    area: "Eastern Ukraine",
    port: false,
  },
  {
    name: "Porto",
    type: "city",
    top: "68.96",
    left: "18.33",
    size: "small",
    kingdomCaptial: "Lisboa",
    map: "main",
    area: "Portugal",
    port: true,
  },
  {
    name: "Postdam",
    type: "city",
    top: "35.3",
    left: "52.48",
    size: "small",
    kingdomCaptial: "Berlin",
    map: "main",
    area: "Brandenburg",
    port: false,
  },
  {
    name: "Poznan",
    type: "city",
    top: "37.35",
    left: "58.09",
    size: "small",
    kingdomCaptial: "Krakow",
    map: "main",
    area: "Wielkopolska",
    port: false,
  },
  {
    name: "Pozsony",
    type: "city",
    top: "48.85",
    left: "59.59",
    size: "small",
    kingdomCaptial: "Pest",
    map: "main",
    area: "Royal Hungary",
    port: false,
  },
  {
    name: "Praha",
    type: "city",
    top: "43.23",
    left: "54.98",
    size: "large",
    kingdomCaptial: "Praha",
    map: "main",
    area: "Bohemia",
    port: false,
  },
  {
    name: "Provence",
    type: "city",
    top: "64.81",
    left: "41.07",
    size: "large",
    kingdomCaptial: "Provence",
    map: "main",
    area: "Languedoc",
    port: true,
  },
  {
    name: "Pskov",
    type: "city",
    top: "20.44",
    left: "74",
    size: "small",
    kingdomCaptial: "Pskov",
    map: "main",
    area: "Novgorod",
    port: false,
  },
  {
    name: "Qafsah",
    type: "city",
    top: "93.5",
    left: "45.3",
    size: "small",
    kingdomCaptial: "Qafsah",
    map: "main",
    area: "North Sahara",
    port: true,
  },
  {
    name: "Qahirah",
    type: "city",
    top: "93.5",
    left: "76.6",
    size: "large",
    kingdomCaptial: "Qahirah",
    map: "expansion",
    area: "Egypt",
    port: false,
  },
  {
    name: "Quito",
    type: "city",
    top: "16.5",
    left: "4.7",
    size: "small",
    kingdomCaptial: "Cuzco",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Ragusa",
    type: "city",
    top: "67.4",
    left: "59.4",
    size: "small",
    kingdomCaptial: "Ragusa",
    map: "main",
    area: "Dalmatia",
    port: true,
  },
  {
    name: "Ragensburg",
    type: "city",
    top: "46.1",
    left: "51.1",
    size: "small",
    kingdomCaptial: "Munchen",
    map: "main",
    area: "Bavaria Swabia",
    port: false,
  },
  {
    name: "Rennes",
    type: "city",
    top: "47.5",
    left: "28.1",
    size: "small",
    kingdomCaptial: "Nantes",
    map: "main",
    area: "Brittany Normandy",
    port: true,
  },
  {
    name: "Reval",
    type: "city",
    top: "17.3",
    left: "69.2",
    size: "small",
    kingdomCaptial: "Livland",
    map: "main",
    area: "Estonia Livonia",
    port: true,
  },
  {
    name: "Rhodes",
    type: "city",
    top: "83.5",
    left: "73.6",
    size: "small",
    kingdomCaptial: "Rhodes",
    map: "main",
    area: "Aegean Archipelago",
    port: true,
  },
  {
    name: "Riga",
    type: "city",
    top: "23.2",
    left: "68.7",
    size: "small",
    kingdomCaptial: "Riga",
    map: "main",
    area: "Estonia Livonia",
    port: true,
  },
  {
    name: "Rijeka",
    type: "city",
    top: "60.7",
    left: "55.3",
    size: "small",
    kingdomCaptial: "Zagreb",
    map: "main",
    area: "Dalmatia",
    port: true,
  },
  {
    name: "Rio de Janeiro",
    type: "territory",
    top: "21.7",
    left: "9.7",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Roma",
    type: "city",
    top: "71.1",
    left: "51.7",
    size: "large",
    kingdomCaptial: "Roma",
    map: "main",
    area: "Central Italy",
    port: true,
  },
  {
    name: "Rudohori",
    type: "city",
    top: "42.7",
    left: "53.6",
    size: "small",
    kingdomCaptial: "Praha",
    map: "main",
    area: "Bohemia",
    port: false,
  },
  {
    name: "Ryazan",
    type: "city",
    top: "34.1",
    left: "87.8",
    size: "small",
    kingdomCaptial: "Ryazan",
    map: "expansion",
    area: "Moscow Ryazan",
    port: false,
  },
  {
    name: "Rzkhev",
    type: "city",
    top: "25.5",
    left: "81.1",
    size: "small",
    kingdomCaptial: "Moskva",
    map: "expansion",
    area: "Moscow Ryazan",
    port: false,
    only: 1444,
  },
  {
    name: "Saintonge",
    type: "city",
    top: "54.8",
    left: "30.5",
    size: "small",
    kingdomCaptial: "Paris",
    map: "main",
    area: "Aquitaine",
    port: true,
  },
  {
    name: "Salamanca",
    type: "city",
    top: "69.8",
    left: "21.6",
    size: "large",
    kingdomCaptial: "Madrid",
    map: "main",
    area: "Leon",
    port: false,
  },
  {
    name: "Salerno",
    type: "city",
    top: "76.5",
    left: "56.5",
    size: "small",
    kingdomCaptial: "Napoli",
    map: "main",
    area: "Naples",
    port: true,
  },
  {
    name: "Salzburg",
    type: "city",
    top: "50.8",
    left: "52.5",
    size: "small",
    kingdomCaptial: "Salzburg",
    map: "main",
    area: "Bavaria Swabia",
    port: false,
  },
  {
    name: "Samarkand",
    type: "city",
    top: "54",
    left: "4.4",
    size: "large",
    kingdomCaptial: "Samarkand",
    map: "distant",
    area: "India Arabia",
    port: false,
  },
  {
    name: "Sandomierz",
    type: "city",
    top: "43.5",
    left: "65.1",
    size: "small",
    kingdomCaptial: "Moskva",
    map: "main",
    area: "Mazovia Malopolska",
    port: false,
    only: 1444,
  },
  {
    name: "Sarai",
    type: "city",
    top: "49.7",
    left: "95.5",
    size: "small",
    kingdomCaptial: "Saratov",
    map: "expansion",
    area: "Astrakhan",
    port: false,
  },
  {
    name: "Saratov",
    type: "city",
    top: "42.4",
    left: "94.9",
    size: "small",
    kingdomCaptial: "Saratov",
    map: "expansion",
    area: "Saratov",
    port: false,
  },
  {
    name: "Sardenya",
    type: "city",
    top: "77.6",
    left: "46.6",    
    size: "small",
    kingdomCaptial: "Valencia",
    map: "main",
    area: "Corsica Sardinia",
    port: true,
  },
  {
    name: "Savoie",
    type: "city",
    top: "57.1",
    left: "41.6",
    size: "large",
    kingdomCaptial: "Savoie",
    map: "main",
    area: "Burgundy",
    port: false,
  },
  {
    name: "Selanik",
    type: "city",
    top: "72.3",
    left: "67.3",
    size: "small",
    kingdomCaptial: "Edirne",
    map: "expansion",
    area: "Macedonia Thrace",
    port: true,
  },
  {
    name: "Sevilla",
    type: "city",
    top: "79.5",
    left: "21.6",
    size: "large",
    kingdomCaptial: "Madrid",
    map: "main",
    area: "Andalucia",
    port: true,
  },
  {
    name: "Shirvan",
    type: "city",
    left: "97.8",
    top: "64.8",
    size: "small",
    kingdomCaptial: "Shirvan",
    map: "expansion",
    area: "Caucasus",
    port: false,
  },
  {
    name: "Shrewsbury",
    type: "city",
    top: "32.3",
    left: "27.9",
    size: "small",
    kingdomCaptial: "London",
    map: "main",
    area: "Wales Essex",
    port: false,
  },
  {
    name: "Siam",
    type: "city",
    top: "78",
    left: "1.3",
    size: "large",
    kingdomCaptial: "Siam",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "Siena",
    type: "city",
    top: "68.7",
    left: "50.1",
    size: "small",
    kingdomCaptial: "Siena",
    map: "main",
    area: "Central Italy",
    port: true,
  },
  {
    name: "Sieradz",
    type: "city",
    top: "41.6",
    left: "61",
    size: "small",
    kingdomCaptial: "Sieradz",
    map: "main",
    area: "Wielkopolska",
    port: false,
  },
  {
    name: "Silesia",
    type: "city",
    top: "41.6",
    left: "58.3",
    size: "small",
    kingdomCaptial: "Silesia",
    map: "main",
    area: "Wielkopolska",
    port: false,
  },
  {
    name: "Silistre",
    type: "city",
    top: "63.5",
    left: "74.2",
    size: "small",
    kingdomCaptial: "Edirne",
    map: "expansion",
    area: "Wallachia Bulgaria",
    port: true,
  },
  {
    name: "Sivas",
    type: "city",
    top: "73.5",
    left: "85.6",
    size: "small",
    kingdomCaptial: "Sivas",
    map: "expansion",
    area: "Rum",
    port: false,
    only: 1444,
  },
  {
    name: "Slesvig",
    type: "city",
    top: "26.9",
    left: "46.8",
    size: "small",
    kingdomCaptial: "Holstein",
    map: "main",
    area: "Jutland",
    port: true,
  },
  {
    name: "Smederevo",
    type: "city",
    top: "62.3",
    left: "65.2",
    size: "small",
    kingdomCaptial: "Smederevo",
    map: "main",
    area: "Serbia Albania",
    port: false,
    only: 1444,
  },
  {
    name: "Smolenskas",
    type: "city",
    top: "32.4",
    left: "79.2",
    size: "small",
    kingdomCaptial: "Vilnius",
    map: "main",
    area: "White Ruthenia",
    port: false,
  },
  {
    name: "Sofya",
    type: "city",
    top: "65.5",
    left: "69",
    size: "small",
    kingdomCaptial: "Edirne",
    map: "expansion",
    area: "Wallachia Bulgaria",
    port: false,
  },
  {
    name: "Songhai",
    type: "city",
    top: "34.6",
    left: "2.9",
    size: "large",
    kingdomCaptial: "Songhai",
    map: "distant",
    area: "Africa",
    port: false,
  },
  {
    name: "Sopron",
    type: "city",
    top: "52.5",
    left: "58.6",
    size: "small",
    kingdomCaptial: "Pest",
    map: "main",
    area: "Royal Hungary",
    port: false,
  },
  {
    name: "Sousse",
    type: "city",
    top: "88.8",
    left: "48.2",
    size: "small",
    kingdomCaptial: "Tunis",
    map: "main",
    area: "Tunisia",
    port: true,
  },
  {
    name: "Southern Australia",
    type: "territory",
    top: "93.7",
    left: "9.2",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "South Sumatra",
    type: "territory",
    top: "84.9",
    left: "1.8",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "St. Gallen",
    type: "city",
    top: "52.6",
    left: "46.3",
    size: "small",
    kingdomCaptial: "Bern",
    map: "main",
    area: "Switzerland",
    port: false,
  },
  {
    name: "Steiermark",
    type: "city",
    top: "53",
    left: "54.7",
    size: "small",
    kingdomCaptial: "Wien",
    map: "main",
    area: "Austria",
    port: false,
  },
  {
    name: "Stettin",
    type: "city",
    top: "31.3",
    left: "55.7",
    size: "small",
    kingdomCaptial: "Stettin",
    map: "main",
    area: "Pomerania",
    port: true,
  },
  {
    name: "Stockholm",
    type: "city",
    top: "14.5",
    left: "60.2",
    size: "small",
    kingdomCaptial: "Stockholm",
    map: "main",
    area: "Svealand",
    port: true,
  },
  {
    name: "Stralsund",
    type: "city",
    top: "29.4",
    left: "53.6",
    size: "small",
    kingdomCaptial: "Stettin",
    map: "main",
    area: "Pomerania",
    port: true,
  },
  {
    name: "Suceava",
    type: "city",
    top: "53.9",
    left: "73.5",
    size: "small",
    kingdomCaptial: "Suceava",
    map: "main",
    area: "Moldavia",
    port: false,
  },
  {
    name: "Sungdau",
    type: "city",
    top: "50",
    left: "43.5",
    size: "small",
    kingdomCaptial: "Wien",
    map: "distant",
    area: "Rhineland",
    port: false,
  },
  {
    name: "Sus",
    type: "city",
    top: "94.9",
    left: "22.2",
    size: "small",
    kingdomCaptial: "Fez",
    map: "main",
    area: "Suthern Morocco",
    port: false,
  },
  {
    name: "Suzdal",
    type: "city",
    top: "25.4",
    left: "90.3",
    size: "small",
    kingdomCaptial: "Moskva",
    map: "expansion",
    area: "Central Russia",
    port: false,
  },
  {
    name: "Szabolcs",
    type: "city",
    top: "51.9",
    left: "64.9",
    size: "small",
    kingdomCaptial: "Pest",
    map: "main",
    area: "Hungarian Plain",
    port: false,
  },
  {
    name: "Szepes",
    type: "city",
    top: "48.6",
    left: "62.8",
    size: "small",
    kingdomCaptial: "Pest",
    map: "main",
    area: "Royal Hungary",
    port: false,
  },
  {
    name: "Tabriz",
    type: "city",
    top: "76.6",
    left: "96.3",
    size: "large",
    kingdomCaptial: "Tabriz",
    map: "expansion",
    area: "Armenia",
    port: false,
  },
  {
    name: "Tafilalt",
    type: "city",
    top: "94.3",
    left: "25.4",
    size: "small",
    kingdomCaptial: "Fez",
    map: "main",
    area: "Suthern Morocco",
    port: false,
  },
  {
    name: "Tambov",
    type: "city",
    top: "38.8",
    left: "89.8",
    size: "small",
    kingdomCaptial: "Saratov",
    map: "expansion",
    area: "Saratov",
    port: false,
  },
  {
    name: "Talgiers",
    type: "city",
    top: "86.2",
    left: "22.4",
    size: "small",
    kingdomCaptial: "Fez",
    map: "main",
    area: "Northern Morocco",
    port: true,
  },
  {
    name: "Tarabulus",
    type: "city",
    top: "83.5",
    left: "84.3",
    size: "small",
    kingdomCaptial: "Qahirah",
    map: "expansion",
    area: "Syria",
    port: true,
  },
  {
    name: "Tblisi",
    type: "city",
    top: "67.2",
    left: "94.3",
    size: "small",
    kingdomCaptial: "Tbilisi",
    map: "expansion",
    area: "Armenia",
    port: false,
  },
  {
    name: "Teke",
    type: "city",
    top: "80.4",
    left: "77.2",
    size: "small",
    kingdomCaptial: "Edirne",
    map: "expansion",
    area: "Aydin",
    port: true,
  },
  {
    name: "Terek",
    type: "city",
    top: "60.6",
    left: "95.4",
    size: "small",
    kingdomCaptial: "Saratov",
    map: "expansion",
    area: "Caucasus",
    port: false,
  },
  {
    name: "Tikrit",
    type: "city",
    top: "83.7",
    left: "93.4",
    size: "small",
    kingdomCaptial: "Tabriz",
    map: "expansion",
    area: "Iraq",
    port: false,
  },
  {
    name: "Timbuktu",
    type: "city",
    top: "33.6",
    left: "1.7",
    size: "small",
    kingdomCaptial: "Timbuktu",
    map: "distant",
    area: "Africa",
    port: false,
  },
  {
    name: "Timor",
    type: "territory",
    top: "86.3",
    left: "5.7",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "Tirgoviste",
    type: "city",
    top: "61",
    left: "70.2",
    size: "small",
    kingdomCaptial: "Tirgoviste",
    map: "expansion",
    area: "Wallachia Bulgaria",
    port: false,
  },
  {
    name: "Tirol",
    type: "city",
    top: "52.8",
    left: "49.3",
    size: "small",
    kingdomCaptial: "Wien",
    map: "main",
    area: "Tirol",
    port: false,
  },
  {
    name: "Tlemcen",
    type: "city",
    top: "87.7",
    left: "30.4",
    size: "small",
    kingdomCaptial: "Tlemcen",
    map: "main",
    area: "Algiers",
    port: true,
  },
  {
    name: "Torda",
    type: "city",
    top: "55",
    left: "68.9",
    size: "small",
    kingdomCaptial: "Pest",
    map: "main",
    area: "Transylvania",
    port: false,
  },
  {
    name: "Toulouse",
    type: "city",
    top: "63.5",
    left: "35.2",
    size: "small",
    kingdomCaptial: "Paris",
    map: "main",
    area: "Languedoc",
    port: false,
  },
  {
    name: "Trebizond",
    type: "city",
    top: "70.3",
    left: "88.2",
    size: "small",
    kingdomCaptial: "Trebizond",
    map: "expansion",
    area: "Rum",
    port: true,
  },
  {
    name: "Treviso",
    type: "city",
    top: "57.6",
    left: "52.3",
    size: "small",
    kingdomCaptial: "Venezia",
    map: "main",
    area: "Venetia",
    port: false,
  },
  {
    name: "Trier",
    type: "city",
    top: "43.6",
    left: "43.2",
    size: "small",
    kingdomCaptial: "Trier",
    map: "main",
    area: "Westphalia",
    port: false,
  },
  {
    name: "Tripoli",
    type: "city",
    top: "94",
    left: "52.4",    
    size: "small",
    kingdomCaptial: "Tunis",
    map: "expansion",
    area: "Tripolitania",
    port: true,
  },
  {
    name: "Trondheim",
    type: "city",
    top: "2.7",
    left: "50.5",
    size: "small",
    kingdomCaptial: "Akershus",
    map: "main",
    area: "Trondelag",
    port: true,
  },
  {
    name: "Tunis",
    type: "city",
    top: "85.2",
    left: "48.1",
    size: "small",
    kingdomCaptial: "Tunis",
    map: "main",
    area: "Tunisia",
    port: true,
  },
  {
    name: "Tver",
    type: "city",
    top: "26.1",
    left: "83.9",
    size: "small",
    kingdomCaptial: "Tver",
    map: "main",
    area: "Moscow Ryazan",
    port: false,
  },
  {
    name: "Tyumen",
    type: "city",
    top: "4.4",
    left: "86.2",
    size: "large",
    kingdomCaptial: "Tyumen",
    map: "distant",
    area: "Northern Central Asia",
    port: false,
  },
  {
    name: "Ulaidh",
    type: "city",
    top: "24.4",
    left: "20.4",
    size: "small",
    kingdomCaptial: "Ulaidh",
    map: "main",
    area: "Ireland",
    port: true,
  },
  {
    name: "Ulm",
    type: "city",
    top: "47.2",
    left: "47.5",
    size: "small",
    kingdomCaptial: "Ulm",
    map: "main",
    area: "Bavaria Swabia",
    port: false,
  },
  {
    name: "Upper Egypt",
    type: "city",
    top: "32.7",
    left: "7.3",
    size: "small",
    kingdomCaptial: "Qahirah",
    map: "distant",
    area: "Africa",
    port: true,
  },
  {
    name: "Ural",
    type: "territory",
    top: "1.8",
    left: "84.9",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "Northern Central Asia",
    port: false,
  },
  {
    name: "Urfa",
    type: "city",
    top: "78.7",
    left: "88.3",
    size: "small",
    kingdomCaptial: "Mush",
    map: "expansion",
    area: "Kurdistan",
    port: false,
  },
  {
    name: "Valencia",
    type: "city",
    top: "73.4",
    left: "30.8",
    size: "large",
    kingdomCaptial: "Valencia",
    map: "expansion",
    area: "Aragon",
    port: false,
  },
  {
    name: "Verona",
    type: "city",
    top: "59.3",
    left: "50.5",  
    size: "small",
    kingdomCaptial: "Venezia",
    map: "main",
    area: "Venetia",
    port: false,
  },
  {
    name: "Vestjylland",
    type: "city",
    top: "22",
    left: "45.4",
    size: "small",
    kingdomCaptial: "Kobenhavn",
    map: "main",
    area: "Jutland",
    port: true,
  },
  {
    name: "Viatka",
    type: "city",
    top: "20.7",
    left: "96.8",
    size: "small",
    kingdomCaptial: "Mosvka",
    map: "expansion",
    area: "Perm",
    port: false,
  },
  {
    name: "Vilnius",
    type: "city",
    top: "32.8",
    left: "69.9",
    size: "small",
    kingdomCaptial: "Vilnius",
    map: "main",
    area: "Lithuania",
    port: false,
  },
  {
    name: "Virginia",
    type: "territory",
    top: "6.3",
    left: "4.9",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "America",
    port: true,
  },
  {
    name: "Vladmir",
    type: "city",
    top: "30.1",
    left: "88.8",
    size: "small",
    kingdomCaptial: "Moskva",
    map: "expansion",
    area: "Central Russia",
    port: false,
  },
  {
    name: "Vogelkop",
    type: "territory",
    top: "83.9",
    left: "7.6",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "Vologda",
    type: "city",
    top: "18.6",
    left: "87.2",
    size: "small",
    kingdomCaptial: "Moskva",
    map: "main",
    area: "Vologda",
    port: false,
  },
  {
    name: "Voluine",
    type: "city",
    top: "40.8",
    left: "69.5",
    size: "small",
    kingdomCaptial: "Vilnius",
    map: "main",
    area: "Red Ruthenia",
    port: false,
  },
  {
    name: "Wales",
    type: "city",
    top: "34",
    left: "25.1",
    size: "small",
    kingdomCaptial: "London",
    map: "main",
    area: "Wales Essex",
    port: true,
  },
  {
    name: "Warszawa",
    type: "city",
    top: "37.8",
    left: "65.6",
    size: "small",
    kingdomCaptial: "Warszawa",
    map: "main",
    area: "Mazovia Malopolska",
    port: false,
  },
  {
    name: "Wessex",
    type: "city",
    top: "39.3",
    left: "26.6",
    size: "small",
    kingdomCaptial: "London",
    map: "main",
    area: "Wales Essex",
    port: true,
  },
  {
    name: "Western Australia",
    type: "territory",
    top: "92.4",
    left: "5.1",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "Far East",
    port: true,
  },
  {
    name: "West Siberia",
    type: "territory",
    top: "1.7",
    left: "88.2",
    size: "small",
    kingdomCaptial: "",
    map: "distant",
    area: "Northern Central Asia",
    port: false,
  },
  {
    name: "Wien",
    type: "city",
    top: "50.5",
    left: "56.5",
    size: "large",
    kingdomCaptial: "Wien",
    map: "main",
    area: "Austria",
    port: false,
  },
  {
    name: "Wittenberg",
    type: "city",
    top: "38.3",
    left: "52.1",
    size: "small",
    kingdomCaptial: "Dresden",
    map: "main",
    area: "Saxony",
    port: false,
  },
  {
    name: "Xian",
    type: "city",
    top: "71.2",
    left: "2.1",
    size: "large",
    kingdomCaptial: "Beijing",
    map: "distant",
    area: "Far East",
    port: false,
  },
  {
    name: "Yanya",
    type: "city",
    top: "76.8",
    left: "65.1",
    size: "small",
    kingdomCaptial: "Edirne",
    map: "expansion",
    area: "Greece",
    port: true,
  },
  {
    name: "Yaroslavl",
    type: "city",
    top: "22.9",
    left: "87.2",
    size: "small",
    kingdomCaptial: "Yaroslavl",
    map: "expansion",
    area: "Central Russia",
    port: false,
  },
  {
    name: "Yedi-Shkul",
    type: "city",
    top: "54.7",
    left: "83.4",
    size: "small",
    kingdomCaptial: "Crimea",
    map: "expansion",
    area: "Crimea",
    port: false,
    only: 1444
  },
  {
    name: "Yemen",
    type: "city",
    top: "63.9",
    left: "1",
    size: "small",
    kingdomCaptial: "Yemen",
    map: "distant",
    area: "India Arabia",
    port: true,
  },
  {
    name: "Yeravan",
    type: "city",
    top: "71.8",
    left: "94.4",
    size: "small",
    kingdomCaptial: "Erevan",
    map: "expansion",
    area: "Armenia",
    port: false,
  },
  {
    name: "Zagreb",
    type: "city",
    top: "57.2",
    left: "58.6",
    size: "small",
    kingdomCaptial: "Zagreb",
    map: "main",
    area: "Croatia Bosnia",
    port: false,
  },
  {
    name: "Zara",
    type: "city",
    top: "64.7",
    left: "56.7",
    size: "small",
    kingdomCaptial: "Venetia",
    map: "main",
    area: "Dalmatia",
    port: true,
  },
  {
    name: "Zaragoza",
    type: "city",
    top: "68.8",
    left: "31.4",
    size: "small",
    kingdomCaptial: "Valencia",
    map: "main",
    area: "Aragon",
    port: false,
  },
  {
    name: "Zeeland",
    type: "city",
    top: "36.3",
    left: "38.6",
    size: "small",
    kingdomCaptial: "Amsterdam",
    map: "main",
    area: "Netherlands",
    port: true,
  },
  {
    name: "Zemaitija",
    type: "city",
    top: "27.1",
    left: "67.2",
    size: "small",
    kingdomCaptial: "Vilnius",
    map: "main",
    area: "Lithuania",
    port: false,
  },
  {
    name: "Beloozero",
    type: "city",
    top: "14.5",
    left: "85.2",
    size: "small",
    kingdomCaptial: "Beloozero",
    map: "main",
    area: "Vologda",
    port: false,
  },
];
